<?php

namespace Database\Seeders;

use App\Models\BoardGame;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BoardGameSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $games = [
            [
                'kode' => '18/Y/PK/1/LT-3',
                'box' => 1,
                'nama' => 'Yak',
                'penerbit' => 'PLAN 8 GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTftXBVJwXXKMV9fjk_ffhi-7DRae8zmmKlG9EQT7VRwA&s', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgvMm6MuTaNqkbKJQG4c0lMynnlAIkBHD6LnzrDZyWI0hDar4YkiVXY_g&s=10'],
                'komponen' => '1 rulebook, 1 Punchboard front, 1 game board, 1 bag, 1 score pad, 1 baby yag, 4 yag besar, 4 keranjang, 4 player boards, 1 mountain, 1 stupa marker, 1 awan, 8 carts panel, 8 roda, 5 fogs (batu putih), 45 food token (15 roti (kuning), 15 susu (putih), 15 ayam (coklat)), 20 cards (12 action, 8 bonus), 8 batu kristal (biru muda), 64 batu warna (8 kuning, 8 jingga, 8 orange, 8 merah, 8 biru tua, 8 abu tua, 8 abu muda), 8 tanduk putih',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '20/I/PK/1/LT-2',
                'box' => 1,
                'nama' => 'Imhotep',
                'penerbit' => 'KOSMOS',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://zatu.com/cdn/shop/files/Imhotep_grande.jpg?v=1760984874', 'https://modelshop.com.mt/wp-content/uploads/2021/09/imhotep-board-game-2.jpg'],
                'komponen' => '120 wooden cubes (kubus kayu), 5 site boards (papan lokasi), 1 scoring track (papan jalur skor), 8 ship tokens (token kapal), 4 supply sled tokens (token kereta luncur logistik), 21 round cards (kartu ronde), 34 market cards (kartu pasar), 1 rule booklet (buku peraturan).',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '23/U/PK/1/LT-1',
                'box' => 1,
                'nama' => 'Ubongo',
                'penerbit' => 'KOSMOS',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://levelupstore.co.za/cdn/shop/products/699345_1_1200x.jpg?v=1676116824', 'https://thamesandkosmos.com/cdn/shop/products/Ubongo3D_Contents2.jpg?v=1663616998'],
                'komponen' => '4x12 Ubin, 36 Papan Puzzle, 1 Dadu, 1 Jam Pasir, 1 Kantong Kain, 1 Trek Ronde Permainan, 58 Permata: 19 Safir (biru), 19 Amber (coklat), 10 Rubi (merah), 10 Zamrud (hijau)',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '28/1830RRB/PK/1/LT-1',
                'box' => 1,
                'nama' => '1830 : Railways & Robber Barons (1986)',
                'penerbit' => 'LOOK OUT GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.doubledanegames.com/wp-content/uploads/2022/11/sq-1830-box.jpg', 'https://store.asmodee.com/cdn/shop/products/LK0043-3_400x@2x.jpg?v=1691184549'],
                'komponen' => '1 double-sided gameboard (papan permainan dua sisi), 117 cards (kartu), 8 corporate charters (piagam perusahaan), 1 stack of money (tumpukan uang), 85 hexagonal tiles (ubin heksagonal), 25 circular tokens (token berbentuk lingkaran), 25 square markers (penanda berbentuk persegi), 1 rulebook (buku peraturan).',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '42/BN/PK/1/LT-1',
                'box' => 1,
                'nama' => 'Block Ness',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://boardgamesq8.com/image/cache/catalog/InShot20221214161130779-800x800.jpg', 'https://m.media-amazon.com/images/I/81DPrfZdPTS._AC_SL1500_.jpg'],
                'komponen' => '1 papan Loch, 4 monster dengan warna berbeda (masing-masing terdiri dari 12 bagian: 1 kepala, 10 segmen tubuh, dan 1 ekor), buku aturan bergambar dalam 8 bahasa.',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '49/ML/PK/1/LT-1',
                'box' => 1,
                'nama' => 'Meeple Land',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2020/09/MeepleLand-3DBox-thegem-blog-timeline-large.png', 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//90/MTA-20106277/blue_orange_meeple_land_board_game_full02_mpyr6eyf.jpg'],
                'komponen' => '4 papan Plot individu, 1 papan Parking Lot, 4 ubin Plot Extension, 4 pintu masuk taman tambahan, 101 ubin Attraction/Service (32 ubin kecil dengan iklan di bagian belakang, 40 ubin sedang, dan 29 ubin besar), 17 ubin Bus, 124 Meeple Pengunjung (35 hijau, 35 biru, 30 merah muda, dan 24 kuning), 1 token Park Tickets (token pemain pertama), 1 penanda ronde, 52 koin (33 koin $1, 19 koin $5), 4 pintu masuk taman pemain (2 pilar dan 1 banner per pemain), 1 buku catatan skor, Rules Book dalam 7 Bahasa',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '54/P/PK/1/LT-2',
                'box' => 1,
                'nama' => 'Photosynthesis',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.calendarclub.ca/cdn/shop/products/Photosynthesis.jpg?v=1756406827', 'https://www.rei.com/media/955fa38e-6970-40c1-87a4-86050410ef27.jpg?size=784x588'],
                'komponen' => '1 Papan Permainan, 1 Segmen Matahari, 4 Papan Pemain, 1 Token Pemain Pertama, 24 Token Skor, 4 Token Penanda Matahari, 4 Token dengan Angka (1-4), 24 Token Biji (6 tiap spesies), 32 Pohon Kecil (8 tiap spesies), 16 Pohon Sedang (4 tiap spesies), 8 Pohon Besar (2 tiap spesies), Aturan Bergambar, 4 Kardus segmen',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '3/P/PK/2/LT-2',
                'box' => 2,
                'nama' => 'Pengoloo',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://i5.walmartimages.com/seo/Blue-Orange-Games-Pengoloo-Wooden-Memory-Building-Game-For-Kids_ab099095-3346-4efd-8c6c-a013a25d7ce0.10dbde98b8153a8ee325b59a7c226272.jpeg', 'https://images.thenile.io/r1000/0803979002705.jpg'],
                'komponen' => '12 penguins, 12 telur (2 merah, 2 kuning, 2 hijau, 2 biru, 2 ungu, 2 orange), 1 rules book, 4 score board, 2 dadu',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '9/TO/PK/2/LT-3',
                'box' => 2,
                'nama' => 'Tongues Out',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpXWmeVetPLG1R43VQg0KpYkCdwxNIc0VG5u6gzFjVFP-Knl-sHUntpXk&s=10', 'https://cdn.ruparupa.io/fit-in/400x400/filters:format(webp)/filters:quality(90)/ruparupa-com/image/upload/Products/10655701_2.jpg'],
                'komponen' => '12 dogs, 1 rules book, 4 kartu, 2 dadu',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '15/TM/PK/2/LT-3',
                'box' => 2,
                'nama' => 'The Mind',
                'penerbit' => 'AMIGO/SWAN',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://store.asmodee.com/cdn/shop/files/PAN202109-image0_2000.jpg?v=1760644366', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVSJPeYxskcf3ZvOQyqkajZjRzWRBE5BdV3S5s9LxI4Q&s=10'],
                'komponen' => '120 Kartu, 1 Panduan bermain',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '16/TN7/PK/2/LT-1',
                'box' => 2,
                'nama' => 'The Nasty 7',
                'penerbit' => 'AMIGO/SWAN',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://theboardbartender.ca/cdn/shop/products/TheNasty7.jpg?v=1628450821', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlhUBkjHvChC4BWCwJv0acl1AorFjQEfvJGVU1eZAIxQ&s'],
                'komponen' => '110 Kartu, 1 Panduan bermain',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '17/ASGOS/PK/2/LT-1',
                'box' => 2,
                'nama' => 'Azul Stained Glass of Sintra',
                'penerbit' => 'PLAN 8 GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://down-id.img.susercontent.com/file/92bb578ede725a6d216728a97aef4267', 'https://down-id.img.susercontent.com/file/sg-11134201-7rd6q-lupxfobdzv9a76'],
                'komponen' => '9 factory displays (pajangan pabrik), 4 palace boards (papan istana), 32 pattern strips (strip pola), 4 glaziers (pengrajin kaca), 8 markers (penanda), 100 pane pieces (keping kaca), 1 scoring board (papan skor), 1 starting player tile (ubin pemain pertama), 1 glass tower (menara kaca), 1 bag (kantong), 1 rulebook (buku peraturan).',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '41/B/PK/2/LT-2',
                'box' => 2,
                'nama' => 'Bendomino',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://i5.walmartimages.com/seo/Blue-Orange-Bendomino-Game-28-Pieces_946f1e85-4b78-4af3-b0e3-afd6c2b9794e_1.5aac88814d3414440b69470026a7335e.jpeg', 'https://blueorangegames.eu/wp-content/uploads/2017/05/Bendomino.jpg'],
                'komponen' => '1 rule book, 28 domino',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '45/CA/PK/2/LT-3',
                'box' => 2,
                'nama' => 'Cupcake Academy',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://i.zst.com.br/thumbs/12/35/19/-1378563286.jpg', 'https://www.m-g.com.au/wp-content/uploads/2021/10/blue-orange-cupcake-academy.png'],
                'komponen' => '8 bahasa rules book, 20 cupcake cups (4 pink, 4 hijau, 4 kuning, 4 biru, 4 orange), 12 plate (3 pink, 3 orange, 3 kuning, 3 biru), 1 shared plate, 1 achievements checklist, 1 jam pasir, 60 card (20 biru, 20 pink, 20 hijau)',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '48/FC/PK/2/LT-2',
                'box' => 2,
                'nama' => 'Fish Club',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.funlearning.co.uk/wp-content/uploads/2021/03/CLD0070-F1.jpg', 'https://m.media-amazon.com/images/I/71TEF1V53sL._AC_SL1500_.jpg'],
                'komponen' => '1 aquarium (akuarium), 9 red fish (ikan merah), 9 blue fish (ikan biru), 4 seahorses (kuda laut), 4 small fish (ikan kecil), 2 clams (kerang), 2 starfish (bintang laut), 1 sticker set (set stiker).',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '57/SM/PK/2/LT-2',
                'box' => 2,
                'nama' => 'Snack Match',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2022/12/SnackMatch-3DBox.jpg', 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/catalog-image/104/MTA-184823186/blue_orange_games_opened_-_snack_match_board_game_no_retur_-_d_full27_eypmtfz4.webp'],
                'komponen' => '6 bahasa rules book, 80 card (72 picnic cards, 8 bonus cards)',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '59/WDI/PK/2/LT-3',
                'box' => 2,
                'nama' => 'Who Did It',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://image.astronauts.cloud/product-images/2024/2/HobbyIndonesiaWhoDidItBoardGame_4be4a486-a87a-458b-b0c0-07982a960f3b_900x900.png', 'https://static.lelekan.ua/image/cache/catalog/igri/hto-napudyv/hto_napudyv_01-800x800.jpg'],
                'komponen' => '13 Poop Token, 8 Rules book, 36 Kartu',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '1/CB/PK/3/LT-1',
                'box' => 3,
                'nama' => 'Cookie Box',
                'penerbit' => 'KOREA PAVILION',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://cf.geekdo-images.com/yf376XCJUCW_lvO3aS3h2w__imagepage/img/z61p-RfRYG7mlzKyPDPvGhfi-js=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3151052.jpg', 'https://cdn.svc.asmodee.net/production-asmodeeit/uploads/image-converter/2022/09/Cookie2-1024x1024.webp'],
                'komponen' => '1 Bel, 30 kartu pesanan, 36 cookies pesanan (9 biru, 9 pink, 9 hijau, 9 ungu)',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '2/K/PK/3/LT-2',
                'box' => 3,
                'nama' => 'Kingdomino',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQByFMyOipn2ZuWjtKFiw0HRkWgjQYG2VliwM_z0NDHEw&s=10', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2M5M2NA2IThNtBdZiOB9bUeeZeawmO9OMIVmFoctuaEoE16ZGK-KuL7c&s=10'],
                'komponen' => '48 Domino, 4 Kartu Persegi, 8 Bidak Kayu, 4 Kastil Karton, 1 Buku Panduan',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '8/TCGCP/PK/3/LT-3',
                'box' => 3,
                'nama' => 'Taco Cat Goat Cheese Pizza',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://m.media-amazon.com/images/I/81FaGDdNgnL.jpg', 'https://s3-ap-southeast-2.amazonaws.com/wc-prod-pim/JPEG_1000x1000/VR76954_C_taco_cat_goat_cheese_pizza_board_game.jpg'],
                'komponen' => '64 Kartu, 2 Panduan Bermain',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '10/GB/PK/3/LT-1',
                'box' => 3,
                'nama' => 'Geistes Blitz',
                'penerbit' => 'AMIGO/SWAN',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://corners.ge/wp-content/uploads/2025/01/Geistesblitz-5-VOR-12.jpg', 'https://redcoast.myshopify.com/cdn/shop/products/product-image-1185587109_1010x.jpg?v=1575424250'],
                'komponen' => '60 Kartu, 1 Ornamen kursi, 1 Ornamen buku, 1 Ornamen tikus, 1 Ornamen botol, 1 Ornamen hantu, 1 Buku panduan',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '19/S/PK/3/LT-3',
                'box' => 3,
                'nama' => 'Specific',
                'penerbit' => 'GIGAMIC',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.tcgpark.com/_next/image?url=https%3A%2F%2Fapi.tcgpark.com%2Fwp-content%2Fuploads%2F2023%2F08%2F3421273427450.jpg&w=3840&q=75', 'https://littlejordantoys.com/wp-content/uploads/2022/03/SPECIFIC1.jpg'],
                'komponen' => '28 Kartu, 3 Dadu, 1 Buku Panduan Bermain',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '26/ATN/PK/3/LT-1',
                'box' => 3,
                'nama' => 'Archaeology: The New',
                'penerbit' => 'Z-MAN GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://cf.geekdo-images.com/GrPuR1uUv8ayILW3V6nTlg__imagepage/img/_yHRKeYowohBm6NQNhoWB5fXIa8=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5426071.jpg', 'https://monstergeekbg.com/cdn/shop/products/original_d843dd9a-9be4-4903-9073-ccdb35174d0f.jpg?v=1628521569'],
                'komponen' => '106 Kartu, 1 Buku panduan bermain, 6 Monument tiles',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '30/P/PK/3/LT-3',
                'box' => 3,
                'nama' => 'Parade',
                'penerbit' => 'Z-MAN GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://zatu.com/cdn/shop/files/ParadeParade-InsideParade-Back_grande.jpg?v=1760985071', 'https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2020/03/Parade-2.jpg'],
                'komponen' => '66 Kartu, 1 Panduan Bermain, 1 Scorepad',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '32/PL/PK/3/LT-2',
                'box' => 3,
                'nama' => 'Project L',
                'penerbit' => 'ASMODEE',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://imgcdn.gamefound.com/extralarge/projects/2912/07548e99-3bb3-4163-b275-6402cf6183e5.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThqgwliUAsNxPsGvNgkEjJBGzmiiuVohAbvWoEFtMjfA&s=10'],
                'komponen' => '32 puzzle putih, 20 puzzle hitam, 90 keping puzzle (masing-masing 10 keping dari 9 bentuk), 4 alas pemain.',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '33/S/PK/3/LT-3',
                'box' => 3,
                'nama' => 'Scout',
                'penerbit' => 'ASMODEE',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://wobgames.net/wp-content/uploads/2022/05/scout-cardgame-japanese-english.webp', 'https://i.etsystatic.com/37518322/r/il/95ccfe/5164435942/il_fullxfull.5164435942_l0jf.jpg'],
                'komponen' => '45 Kartu, 23 Kartu Uang, 30 Koin Angka, 5 Koin Mobil, 1 Koin Segilima, 3 Buku Panduan',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '44/C/PK/3/LT-2',
                'box' => 3,
                'nama' => 'Cubeez',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://cdn11.bigcommerce.com/s-15h1lhwmjz/images/stencil/1280x1280/products/1232/43853/f240fc1c-c166-4cd9-bcc8-7a6115525935__85244.1720411563.PNG?c=1', 'https://cdn11.bigcommerce.com/s-15h1lhwmjz/images/stencil/1280x1280/products/1232/43854/e32c6348-73ed-49f3-a1ef-1bb4a63d5834__20243.1720411562.PNG?c=1'],
                'komponen' => '8 bahasa rules book, 50 challege card, 12 dadu (3 orange, 3 kuning, 3 pink, 3 hijau)',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '51/NSL/PK/3/LT-2',
                'box' => 3,
                'nama' => 'Next Station: London',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2021/12/NSL-Boite-scaled.png', 'https://i.etsystatic.com/42770788/r/il/9ed53c/7273554928/il_570xN.7273554928_sy3p.jpg'],
                'komponen' => '4 Pensil berwarna, 9 Kartu Square, 6 Kartu biru, 5 Kartu merah muda, Kumpulan score sheet, 7 Panduan buku',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '52/PD/PK/3/LT-1',
                'box' => 3,
                'nama' => 'Panic Diner',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2019/04/PanicDiner-3DBox.jpg', 'https://veselosidim.ru/images/detailed/21/lifestyleltd-panic-diner-03.jpg'],
                'komponen' => '1 papan permainan, 1 mesin pencuci piring (tutup kotak), 48 token Piring (dua sisi), 15 token Bintang, 7 token Trofi, 40 kartu Pelanggan (bulat), 20 kartu Tantangan (persegi), 1 timer jam pasir 90 detik, 1 Aturan bergambar dalam 8 Bahasa',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '58/V/PK/3/LT-3',
                'box' => 3,
                'nama' => 'Volto',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.ludijeux.fr/cdn/shop/files/volto_decbb450-9dbe-4d19-a414-d2c87502467f_grande.jpg?v=1719912489', 'https://www.ludijeux.fr/cdn/shop/files/volto-p-image-83142-grande_1024x1024.jpg?v=1719912496'],
                'komponen' => '1 rules book, 20 mask (10 merah, 10 putih), 1 game mat',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '61/C/PK/3/LT-2',
                'box' => 3,
                'nama' => 'Celestia',
                'penerbit' => 'BRG/LBI',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCLoOE42keWJuJV4z8CHx8ohsTbFg8sZTXqy123_R0FQ&s=10', 'https://i0.wp.com/opinionatedgamers.com/wp-content/uploads/2016/03/celestia.jpg?resize=454%2C386&ssl=1'],
                'komponen' => '1 aircraft (pesawat), 6 adventurer pawns (bidak petualang), 6 adventurer tiles (ubin petualang), 9 oval city tiles (ubin kota berbentuk oval), 4 event dice (dadu peristiwa), 1 rulebook (buku peraturan).',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '13/RH/PK/4/LT-3',
                'box' => 4,
                'nama' => 'Rhino Hero',
                'penerbit' => 'AMIGO/SWAN',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.habausa.com/cdn/shop/files/games-rhino-hero-4789-1_720x.jpg?v=1698432047', 'https://m.media-amazon.com/images/I/81AIZostl1L.jpg'],
                'komponen' => '1 rules, 1 fondation, 1 Rhino hero, 28 walls, 31 cards',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '14/SC/PK/4/LT-2',
                'box' => 4,
                'nama' => 'Speed Cups',
                'penerbit' => 'AMIGO/SWAN',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.asdesjeux.com/cdn/shop/products/jeux-enfants-enfants-5-ans-speed-cups-2-fr-1173760705.jpg?v=1750837927', 'https://kassemstore.com/wp-content/uploads/2024/06/7299999082842-3.jpg'],
                'komponen' => '24 picture cards, 20 cups (4 sets of 5 color each),',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '24/TN/PK/4/LT-2',
                'box' => 4,
                'nama' => 'The Number',
                'penerbit' => 'REPOS PRODUCTION',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR_MKKyvSZhlR-xd9UA9GfpoXDuANPMIA47VflmvBWlxDmSurGvJIR3crBqkKMTKOr2mElcDW_c9csz1pZMHGIWqPmpq5pG_V4nX5lbFcCKiWyy57N-0MR6', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQmeKhKwC7ha0-6wCx2iDo-JDJSJ4UwwcwiGexkxF84LvytGoywcad7ko0e_lYLirvkRJzFBA6Km-BXw1eH2gML_WypxQ0TiLBjzJV5BJlpCSWaHRgHx_MG1g'],
                'komponen' => '5 player boards (papan pemain), 5 number tiles (ubin angka), 5 dry-erase markers (spidol yang dapat dihapus), 1 rules book (buku peraturan).',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '29/PB/PK/4/LT-2',
                'box' => 4,
                'nama' => 'Pandemic (Base)',
                'penerbit' => 'Z-MAN GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://zatu.com/cdn/shop/files/Pandemic-2013.jpg?v=1760985299&width=843', 'https://static.gamesmen.com.au/media/catalog/product/cache/57ddbad6affa8d28869fa47188b75842/p/a/pandemic_board_game_4_.jpg'],
                'komponen' => '7 Role Cards, 7 Pawns, 59 Player Cards (48 City cards, 6 Epidemic cards, 5 Event cards), 4 Reference cards, 48 Infection cards, 6 Research Stations. 96 Disease cubes (24 in 4 colors), 4 Cure markers, 1 infection, 1 Outbreaks marker, 1 Board, 1 Rules Book',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '46/DR/PK/4/LT-3',
                'box' => 4,
                'nama' => 'Doctor Rat',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://static.wixstatic.com/media/9b81af_b0fa4867680b49fdb609d644fcf12a7e~mv2.jpg/v1/fill/w_480,h_514,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/9b81af_b0fa4867680b49fdb609d644fcf12a7e~mv2.jpg', 'https://goblingames.mk/wp/wp-content/uploads/2023/12/Doctor-Rat1.jpg'],
                'komponen' => '129 cards (kartu), 5 special action tokens (token aksi khusus), 1 meal counter board (papan penghitung makanan), 1 rat meeple (meeple tikus), 1 trash can token (token tempat sampah), 1 box with a screen and insert (kotak dengan layar dan sisipan), 1 first player token (token pemain pertama), 2 rules books (buku peraturan).',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '55/SE/PK/4/LT-1',
                'box' => 4,
                'nama' => 'Sherlock Express',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//110/MTA-38687546/blue_orange_blue_orange_sherlock_express_board_game_full04_ig6zo7ir.jpg', 'https://m.media-amazon.com/images/I/718y+HUHCgL.jpg'],
                'komponen' => '27 suspect cards, 36 alibi cards, Ilustrated rules 8 Languages',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '60/WW/PK/4/LT-2',
                'box' => 4,
                'nama' => 'Wonder Woods',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://m.media-amazon.com/images/I/71QCU+cTkUL.jpg', 'https://www.bellalunatoys.com/cdn/shop/files/wonder-woods-mushroom-hunting-game-1_1800x1800.jpg?v=1721837851'],
                'komponen' => '35 Keranjang Kayu, 56 Jamur Kayu, 1 Token Pemain Pertama, 4 Papan Lahan Jamur, 16 Kartu Informasi, Aturan Bergambar',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '4/RF/PK/5/LT-3',
                'box' => 5,
                'nama' => 'Ramen Fury',
                'penerbit' => 'MIXLORE',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://image.astronauts.cloud/product-images/2024/1/RamenFuryBoardGame_1b9c47d7-eb58-41a7-a862-e48670871185_900x900.png', 'https://m.media-amazon.com/images/I/91izymg7STL._AC_UF894,1000_QL80_.jpg'],
                'komponen' => '15 kartu Mangkuk Ramen, 89 kartu Bahan, 10 token Sendok, 1 buku instruksi.',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '6/S/PK/5/LT-2',
                'box' => 5,
                'nama' => 'Sequence',
                'penerbit' => 'GOLIATS GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://m.media-amazon.com/images/I/816K0RyrhzL._SL1500_.jpg', 'https://m.media-amazon.com/images/I/81RzQEc0GTL._SL1500_.jpg'],
                'komponen' => '1 instruction card, 1 game board, 104 kartu main, 135 marker chips (35 merah, 50 biru, 50 hijau)',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '7/SIEB/PK/5/LT-2',
                'box' => 5,
                'nama' => 'Spot it (Eco Blister/Peg)',
                'penerbit' => 'ZYGOMATIC',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDxhUT45Pm0bh1tDMnkd40SUeqZD3FhOoCBx6AO-JULWagzV1car-NW8OK&s=10', 'https://store.asmodee.com/cdn/shop/files/SPR103ML-image5_2000_535x.jpg?v=1721231097'],
                'komponen' => '55 Kartu, 1 Kaleng, 1 Buku Panduan, 5 Mini games',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '11/GB/PK/5/LT-3',
                'box' => 5,
                'nama' => 'Get Bit',
                'penerbit' => 'AMIGO/SWAN',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://m.media-amazon.com/images/I/71lJtqKqgdL.jpg_BO30,255,255,255_UF750,750_SR1910,1000,0,C_QL100_.jpg', 'https://shop.greaterthangames.com/cdn/shop/files/GBIT-CORE-2.jpg?v=1761761857&2000w'],
                'komponen' => '6 Figures, 1 Hungry shark, 1 Panduan bermain,',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '22/RL/PK/5/LT-1',
                'box' => 5,
                'nama' => 'Rustling Leaves',
                'penerbit' => 'KOSMOS',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//97/MTA-38026607/kosmos_rustling_leaves_board_game_full01_rbn7p20a.jpg', 'https://zatu.com/cdn/shop/files/Rustling-Leaves-1-3.jpg?v=1760982213&width=500'],
                'komponen' => '1 lembar skor, 2 dadu, 1 Buku Panduan',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '34/TE/PK/5/LT-3',
                'box' => 5,
                'nama' => 'Timeline Events',
                'penerbit' => 'ASMODEE',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.boardgamebliss.com/cdn/shop/products/TIMEECO02EN_1-B.jpg?crop=center&height=1200&v=1611942227&width=1200', 'https://www.gaminglib.com/cdn/shop/products/timeline-events-eco-blister-815651.jpg?v=1702904258'],
                'komponen' => '55 Kartu, 1 Kaleng, 1 Buku Panduan',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '35/TI/PK/5/LT-3',
                'box' => 5,
                'nama' => 'Timeline Inventions',
                'penerbit' => 'ASMODEE',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://cdn.svc.asmodee.net/production-asmodeeit/uploads/2022/09/timeline_invenzioni.png', 'https://www.zygomatic-games.com/wp-content/uploads/2019/08/zigomatic-timeline-inventions-02.jpg'],
                'komponen' => '55 Kartu, 1 Kaleng, 1 Buku Panduan',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '36/WP/PK/5/LT-1',
                'box' => 5,
                'nama' => 'Wrong Party',
                'penerbit' => 'UNSTABLE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNt4_h-pnpT7-XzsCTh2Mfa5CjCAO1rDHn0F2F9RP_9GyfQ659GjlPkMw&s=10', 'https://m.media-amazon.com/images/I/51-3NTjj3JL._SX522_.jpg'],
                'komponen' => '1 Panduan buku, 152 Kartu, 5 Topi party, 1 Score tracker',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '47/DENV/PK/5/LT-2',
                'box' => 5,
                'nama' => 'Dr. Eureka New Version',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://image.astronauts.cloud/product-images/2024/2/HobbyIndonesiaDr_da195624-bc11-4b12-9171-fe92ad2ee9ec_900x900.jpg', 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/catalog-image/106/MTA-167884170/brd-24346_mainan-anak-dr-eureka-board-game_full01-664a62f7.jpg'],
                'komponen' => '8 Buku Panduan Bermain, 54 Kartu, 24, 8 Bola Hijau, 8 Bola Unggu, 8 Bola Merah, 12 Tabung Akrilik',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '50/MR/PK/5/LT-2',
                'box' => 5,
                'nama' => 'Moon River',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2023/07/MoonRiver-3DBox.jpg', 'https://www.toysoupcanada.com/cdn/shop/files/moonriver2_1200x1200.jpg?v=1743438935'],
                'komponen' => '4 reservation boards (papan reservasi), 8 ranchero meeples (meeple ranchero), 96 plots (petak lahan), 20 partner tokens (token mitra), 32 cow meeples (meeple sapi), 2 landscape bonus tiles (ubin bonus lanskap), 1 saloon board (papan saloon), 1 score pad (buku lembar skor).',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '53/PJ/PK/5/LT-1',
                'box' => 5,
                'nama' => 'Pengo Jump',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//catalog-image/119/MTA-95756978/pen_pengo_jump_board_game_full06_p5265j4r.jpeg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTNwp0YxoeMeKdUZ1FFmdAnsV9ln4V8Z0CPUJs0iiDLQ&s'],
                'komponen' => '1 rules book, 1 sea board, 4 penguins, 1 bag, 18 salju, 6 frosty tiles, 6 sea lions beku, 12 sea lions (6 small, 6 large)',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '5/RA/PK/6/LT-2',
                'box' => 6,
                'nama' => 'Resistance Avalon',
                'penerbit' => 'INDIE BOARD & GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://down-id.img.susercontent.com/file/0ef3194c3fb606b4ff03cdc4dff7b48e', 'https://down-id.img.susercontent.com/file/f007f8e1ef1d0d2a5e0a635958bba5f8.webp'],
                'komponen' => '26 Kartu, 25 Karton Kecil, 1 Karton Besar 5 Koin Besar, 2 Koin Kecil, 3 Lembar Tabel Vote, 2 Panduan Bermain',
                'barang_hilang' => null,
                'lantai' => 2,
            ],
            [
                'kode' => '12/HG/PK/6/LT-3',
                'box' => 6,
                'nama' => 'Halli Galli',
                'penerbit' => 'AMIGO/SWAN',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://images.thimbletoys.com/images/items/2030032a1.jpg', 'https://down-id.img.susercontent.com/file/id-11134207-7qukz-lglw98njx4e7d4'],
                'komponen' => '56 Kartu, 1 Bell, 1 Panduan Bermain',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '27/C/PK/6/LT-3',
                'box' => 6,
                'nama' => 'Carcassonne',
                'penerbit' => 'Z-MAN GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvgzX1Nt9MkUIJ8FxZp9UFlmSnZA5XxOv6gehGzkVnM1TXXXCUM_NhvMne&s=10', 'https://i.ebayimg.com/images/g/fnUAAeSwwWFpL2yr/s-l1200.jpg'],
                'komponen' => '84 Ubin Permainan, 1 Papan Bermain, 45 Bidak Kayu, 2 Lembar Panduan Bermain, 2 Brosur Game',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '37/UM/PK/6/LT-1',
                'box' => 6,
                'nama' => 'UNLOCK! Mystery',
                'penerbit' => 'SPACE COWBOYS',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://down-id.img.susercontent.com/file/1e7e8add80b8ab36f49d601df6b9e136', 'https://down-id.img.susercontent.com/file/e6a033c5aaf00e79aaf300fe70a43dd7'],
                'komponen' => '3 Petualangan (186 Kartu), 10 Kartu tutorial, 1 Buku Panduan',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '38/UT/PK/6/LT-3',
                'box' => 6,
                'nama' => 'UNLOCK! Timeless',
                'penerbit' => 'SPACE COWBOYS',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://store.asmodee.com/cdn/shop/products/UNL06-image1_2000_400x@2x.jpg?v=1760644366', 'https://store.asmodee.com/cdn/shop/products/UNL06-image3_2000_400x@2x.jpg?v=1690580048'],
                'komponen' => '10 kartu tutorial, 3 petualangan (180 kartu + 3 lembar kertas), 1 Buku panduan.',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '39/USW/PK/6/LT-1',
                'box' => 6,
                'nama' => 'UNLOCK! Stars Wars',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.m-g.com.au/wp-content/uploads/2022/08/3558380073277_SWU001_Unlock_Star_Wars.jpg', 'https://www.m-g.com.au/wp-content/uploads/2022/08/3558380073277_SWU001_Unlock_Star_Wars_3.jpg'],
                'komponen' => '3 Petualangan (180 Kartu), 1 Booklet, 1 Peta, 10 Kartu tutorial, 1 Lembar kertas, 1 Buku panduan',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '40/S/PK/6/LT-1',
                'box' => 6,
                'nama' => 'Spellbook',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://down-id.img.susercontent.com/file/id-11134207-7r98s-llvosfyte4jwb9', 'https://www.miniaturemarket.com/media/01/54/ef/1752295810/scspel01en-2.jpg'],
                'komponen' => '1 rule book, 1 pouch, 1 altar (warna abu), 1 discard box (kayu coklat), 1 first player token (buku), 4 familiar boards, 4 player aid cards, 84 spell cards, 105 materia token',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '21/P/PK/7/LT-1',
                'box' => 7,
                'nama' => 'Polis',
                'penerbit' => 'KOSMOS',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://i5.walmartimages.com/asr/7b7bdd89-9e1b-4b39-96fa-ad5000cc45b9.6f5722639397c21db57a1d605e9f13ab.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF', 'https://m.media-amazon.com/images/I/61Ry6ZtA1+L.jpg'],
                'komponen' => '1 Papan utama, 2 Papan pribadi, 2 Lembar informasi pemain, 1 Dadu empat sisi, 168 Buah kayu, 14 Ubin Proyek, 4 Lembar, 90 Kartu',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '25/A/PK/7/LT-1',
                'box' => 7,
                'nama' => 'Atiwa',
                'penerbit' => 'LOOKOUT GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSah1Dg3nLDaLPyG4kVSJZ2x9szCyVf3kDrLQzyhCiyQg&s=10', 'https://ugi-games.com/wp-content/uploads/2022/07/14648-lookout-games-atiwa-juego-mesa-espanol-2.jpg'],
                'komponen' => '1 booklet, 1 rule book, 1 action board, 2 action board extention, 4 supply boards, 6 action space, 52 pohon token, 52 family token, 1 start player, 40 gold (25 gold satuan, 15 gold angka 5), 44 polution (22 none, 20 one, 2 two), 1 cloth bag, 1 scoring pad, 88 kartu, 200 wooden pieces (28 kambing putih, 32 friut orange, 32 wild animal beige, 96 fruit bat hitam, 12 player token (3 merah, 3 biru, 3 abu, 3 kuning))',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '31/CB/PK/7/LT-3',
                'box' => 7,
                'nama' => 'Catan (Base)',
                'penerbit' => 'CATAN STUDIO',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://catanshop.com/images/thumbs/0002217_catan-zip_600.jpeg', 'https://www.game.co.uk/images/imgzoom/89/89028999_xxl_a2.jpg'],
                'komponen' => '120 Kartu, 19 Karton Hexagonal, 6 Karton Border, 2 Dadu, 6 Kartu Karton, 24 Koin Karton, 9 Karton Kapal, 36 Rumah Kayu, 1 Pion Kayu, 60 Kayu Balok, 1 Buku Panduan, 1 Brosur, 1 Buku Brosur',
                'barang_hilang' => null,
                'lantai' => 3,
            ],
            [
                'kode' => '43/B/PK/7/LT-1',
                'box' => 7,
                'nama' => 'Brix',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2018/06/Brix-3DBox.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-dIxs62ihpepJPG3ox7qjg4E8qxkD5gBWG113dYxGWl3bWDeW4VsOITo&s=10'],
                'komponen' => '22 bricks (balok), 1 rulebook (buku peraturan).',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
            [
                'kode' => '56/SQ/PK/7/LT-1',
                'box' => 7,
                'nama' => 'Slide Quest',
                'penerbit' => 'BLUE ORANGE GAMES',
                'jumlah' => 1,
                'satuan' => 'set',
                'link_foto' => ['https://www.okkazeo.com/images/jeux/28171.jpg', 'https://down-id.img.susercontent.com/file/1dc611cd381c033cdc746ccef2b2b0ae'],
                'komponen' => '1 papan dengan perangkap, 4 tuas, 20 peta yang menampilkan 4 jenis dunia, 1 ksatria bergulir, 8 rintangan (2 gerbang lengkung, 2 penghalang besar, 2 penghalang kecil, dan 2 batu besar), 9 perangkap (4 dinamit, 4 penjaga bernomor 1 sampai 4, dan 1 penjahat), 1 penghitung nyawa, 3 tingkat kesulitan, 1 penanda "hati", 1 penyelamat permainan, 1 Buku panduan.',
                'barang_hilang' => null,
                'lantai' => 1,
            ],
        ];

        foreach ($games as $game) {
            BoardGame::create($game);
        }
    }
}