<?php

namespace Database\Seeders;

use App\Models\BoardGame;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BoardGameSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $games = [
            [
                'kode' => '18/Y/PK/1',
                'box' => 1,
                'lantai' => 3,
                'nama' => 'Yak',
                'penerbit' => 'Plan B Games',
                'kategori' => 'Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '60-90 Menit',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTftXBVJwXXKMV9fjk_ffhi-7DRae8zmmKlG9EQT7VRwA&s', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgvMm6MuTaNqkbKJQG4c0lMynnlAIkBHD6LnzrDZyWI0hDar4YkiVXY_g&s=10'],
                'komponen' => [
                    ['nama' => 'rulebook', 'jumlah' => 1],
                    ['nama' => 'punchboard', 'jumlah' => 1],
                    ['nama' => 'game board', 'jumlah' => 1],
                    ['nama' => 'bag', 'jumlah' => 1],
                    ['nama' => 'score pad', 'jumlah' => 1],
                    ['nama' => 'baby yak', 'jumlah' => 1],
                    ['nama' => 'yak besar', 'jumlah' => 4],
                    ['nama' => 'keranjang', 'jumlah' => 4],
                    ['nama' => 'player board', 'jumlah' => 4],
                    ['nama' => 'mountain', 'jumlah' => 1],
                    ['nama' => 'stupa marker', 'jumlah' => 1],
                    ['nama' => 'awan', 'jumlah' => 1],
                    ['nama' => 'carts panel', 'jumlah' => 8],
                    ['nama' => 'roda', 'jumlah' => 8],
                    ['nama' => 'fogs', 'jumlah' => 5],
                    ['nama' => 'food token', 'jumlah' => 45],
                    ['nama' => 'cards', 'jumlah' => 20],
                    ['nama' => 'batu kristal', 'jumlah' => 8],
                    ['nama' => 'batu warna', 'jumlah' => 64],
                    ['nama' => 'tanduk putih', 'jumlah' => 8],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '20/I/PK/1',
                'box' => 1,
                'lantai' => 2,
                'nama' => 'Imhotep',
                'penerbit' => 'Kosmos',
                'kategori' => 'Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '40 Menit',
                'link_foto' => ['https://zatu.com/cdn/shop/files/Imhotep_grande.jpg?v=1760984874', 'https://modelshop.com.mt/wp-content/uploads/2021/09/imhotep-board-game-2.jpg'],
                'komponen' => [
                    ['nama' => 'wooden cubes', 'jumlah' => 120],
                    ['nama' => 'site boards', 'jumlah' => 5],
                    ['nama' => 'scoring track', 'jumlah' => 1],
                    ['nama' => 'ship tokens', 'jumlah' => 8],
                    ['nama' => 'supply sled tokens', 'jumlah' => 4],
                    ['nama' => 'round cards', 'jumlah' => 21],
                    ['nama' => 'market cards', 'jumlah' => 34],
                    ['nama' => 'rule booklet', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '23/U/PK/1',
                'box' => 1,
                'lantai' => 1,
                'nama' => 'Ubongo',
                'penerbit' => 'Kosmos',
                'kategori' => 'Puzzle',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '35 Menit',
                'link_foto' => ['https://levelupstore.co.za/cdn/shop/products/699345_1_1200x.jpg?v=1676116824', 'https://thamesandkosmos.com/cdn/shop/products/Ubongo3D_Contents2.jpg?v=1663616998'],
                'komponen' => [
                    ['nama' => 'x12 ubin', 'jumlah' => 4],
                    ['nama' => 'papan puzzle', 'jumlah' => 36],
                    ['nama' => 'dadu', 'jumlah' => 1],
                    ['nama' => 'jam pasir', 'jumlah' => 1],
                    ['nama' => 'kantong kain', 'jumlah' => 1],
                    ['nama' => 'trek ronde', 'jumlah' => 1],
                    ['nama' => 'permata (19 safir, 19 amber, 10 rubi, 10 zamrud)', 'jumlah' => 58],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '28/1830RRB/PK/1',
                'box' => 1,
                'lantai' => 1,
                'nama' => '1830: Railways & Robber Barons',
                'penerbit' => 'Look Out Games',
                'kategori' => 'Strategi Ekonomi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-7 Pemain',
                'durasi' => '180-300 Menit',
                'link_foto' => ['https://www.doubledanegames.com/wp-content/uploads/2022/11/sq-1830-box.jpg', 'https://store.asmodee.com/cdn/shop/products/LK0043-3_400x@2x.jpg?v=1691184549'],
                'komponen' => [
                    ['nama' => 'papan permainan dua sisi', 'jumlah' => 1],
                    ['nama' => 'kartu', 'jumlah' => 117],
                    ['nama' => 'piagam perusahaan', 'jumlah' => 8],
                    ['nama' => 'tumpukan uang', 'jumlah' => 1],
                    ['nama' => 'ubin heksagonal', 'jumlah' => 85],
                    ['nama' => 'token lingkaran', 'jumlah' => 25],
                    ['nama' => 'penanda persegi', 'jumlah' => 25],
                    ['nama' => 'rulebook', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '42/BN/PK/1',
                'box' => 1,
                'lantai' => 1,
                'nama' => 'Block Ness',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Keluarga',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://boardgamesq8.com/image/cache/catalog/InShot20221214161130779-800x800.jpg', 'https://m.media-amazon.com/images/I/81DPrfZdPTS._AC_SL1500_.jpg'],
                'komponen' => [
                    ['nama' => 'papan Loch', 'jumlah' => 1],
                    ['nama' => 'monster warna berbeda (masing-masing 12 bagian)', 'jumlah' => 4],
                    ['nama' => 'buku aturan 8 bahasa', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '49/ML/PK/1',
                'box' => 1,
                'lantai' => 1,
                'nama' => 'Meeple Land',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Manajemen',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-4 Pemain',
                'durasi' => '20-40 Menit',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2020/09/MeepleLand-3DBox-thegem-blog-timeline-large.png', 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//90/MTA-20106277/blue_orange_meeple_land_board_game_full02_mpyr6eyf.jpg'],
                'komponen' => [
                    ['nama' => 'papan Plot', 'jumlah' => 4],
                    ['nama' => 'papan Parking Lot', 'jumlah' => 1],
                    ['nama' => 'ubin Plot Extension', 'jumlah' => 4],
                    ['nama' => 'ubin Attraction/Service', 'jumlah' => 101],
                    ['nama' => 'ubin Bus', 'jumlah' => 17],
                    ['nama' => 'Meeple Pengunjung', 'jumlah' => 124],
                    ['nama' => 'koin', 'jumlah' => 52],
                    ['nama' => 'rules book 7 bahasa', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '54/P/PK/1',
                'box' => 1,
                'lantai' => 2,
                'nama' => 'Photosynthesis',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '60-90 Menit',
                'link_foto' => ['https://www.calendarclub.ca/cdn/shop/products/Photosynthesis.jpg?v=1756406827', 'https://www.rei.com/media/955fa38e-6970-40c1-87a4-86050410ef27.jpg?size=784x588'],
                'komponen' => [
                    ['nama' => 'papan permainan', 'jumlah' => 1],
                    ['nama' => 'segmen matahari', 'jumlah' => 1],
                    ['nama' => 'papan pemain', 'jumlah' => 4],
                    ['nama' => 'token biji', 'jumlah' => 24],
                    ['nama' => 'pohon kecil', 'jumlah' => 32],
                    ['nama' => 'pohon sedang', 'jumlah' => 16],
                    ['nama' => 'pohon besar', 'jumlah' => 8],
                    ['nama' => 'aturan bergambar', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '3/P/PK/2',
                'box' => 2,
                'lantai' => 2,
                'nama' => 'Pengoloo',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Anak & Memori',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://i5.walmartimages.com/seo/Blue-Orange-Games-Pengoloo-Wooden-Memory-Building-Game-For-Kids_ab099095-3346-4efd-8c6c-a013a25d7ce0.10dbde98b8153a8ee325b59a7c226272.jpeg', 'https://images.thenile.io/r1000/0803979002705.jpg'],
                'komponen' => [
                    ['nama' => 'penguin', 'jumlah' => 12],
                    ['nama' => 'telur (6 warna)', 'jumlah' => 12],
                    ['nama' => 'rules book', 'jumlah' => 1],
                    ['nama' => 'score board', 'jumlah' => 4],
                    ['nama' => 'dadu', 'jumlah' => 2],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '9/TO/PK/2',
                'box' => 2,
                'lantai' => 3,
                'nama' => 'Tongues Out',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Party & Reaksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpXWmeVetPLG1R43VQg0KpYkCdwxNIc0VG5u6gzFjVFP-Knl-sHUntpXk&s=10', 'https://cdn.ruparupa.io/fit-in/400x400/filters:format(webp)/filters:quality(90)/ruparupa-com/image/upload/Products/10655701_2.jpg'],
                'komponen' => [
                    ['nama' => 'dogs', 'jumlah' => 12],
                    ['nama' => 'rules book', 'jumlah' => 1],
                    ['nama' => 'kartu', 'jumlah' => 4],
                    ['nama' => 'dadu', 'jumlah' => 2],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '15/TM/PK/2',
                'box' => 2,
                'lantai' => 3,
                'nama' => 'The Mind',
                'penerbit' => 'Amigo/Swan',
                'kategori' => 'Kooperatif',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://store.asmodee.com/cdn/shop/files/PAN202109-image0_2000.jpg?v=1760644366', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVSJPeYxskcf3ZvOQyqkajZjRzWRBE5BdV3S5s9LxI4Q&s=10'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 120],
                    ['nama' => 'panduan bermain', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '16/TN7/PK/2',
                'box' => 2,
                'lantai' => 1,
                'nama' => 'The Nasty 7',
                'penerbit' => 'Amigo/Swan',
                'kategori' => 'Kartu',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '3-6 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://theboardbartender.ca/cdn/shop/products/TheNasty7.jpg?v=1628450821', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlhUBkjHvChC4BWCwJv0acl1AorFjQEfvJGVU1eZAIxQ&s'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 110],
                    ['nama' => 'panduan bermain', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '17/ASGOS/PK/2',
                'box' => 2,
                'lantai' => 1,
                'nama' => 'Azul: Stained Glass of Sintra',
                'penerbit' => 'Plan B Games',
                'kategori' => 'Strategi Abstrak',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '30-45 Menit',
                'link_foto' => ['https://down-id.img.susercontent.com/file/92bb578ede725a6d216728a97aef4267', 'https://down-id.img.susercontent.com/file/sg-11134201-7rd6q-lupxfobdzv9a76'],
                'komponen' => [
                    ['nama' => 'factory display', 'jumlah' => 9],
                    ['nama' => 'palace board', 'jumlah' => 4],
                    ['nama' => 'pattern strip', 'jumlah' => 32],
                    ['nama' => 'glazier', 'jumlah' => 4],
                    ['nama' => 'pane piece', 'jumlah' => 100],
                    ['nama' => 'scoring board', 'jumlah' => 1],
                    ['nama' => 'glass tower', 'jumlah' => 1],
                    ['nama' => 'bag', 'jumlah' => 1],
                    ['nama' => 'rulebook', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '41/B/PK/2',
                'box' => 2,
                'lantai' => 2,
                'nama' => 'Bendomino',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Keluarga',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://i5.walmartimages.com/seo/Blue-Orange-Bendomino-Game-28-Pieces_946f1e85-4b78-4af3-b0e3-afd6c2b9794e_1.5aac88814d3414440b69470026a7335e.jpeg', 'https://blueorangegames.eu/wp-content/uploads/2017/05/Bendomino.jpg'],
                'komponen' => [
                    ['nama' => 'rule book', 'jumlah' => 1],
                    ['nama' => 'domino', 'jumlah' => 28],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '45/CA/PK/2',
                'box' => 2,
                'lantai' => 3,
                'nama' => 'Cupcake Academy',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Anak & Keluarga',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15-20 Menit',
                'link_foto' => ['https://i.zst.com.br/thumbs/12/35/19/-1378563286.jpg', 'https://www.m-g.com.au/wp-content/uploads/2021/10/blue-orange-cupcake-academy.png'],
                'komponen' => [
                    ['nama' => 'bahasa rules book', 'jumlah' => 8],
                    ['nama' => 'cupcake cups', 'jumlah' => 20],
                    ['nama' => 'plate', 'jumlah' => 12],
                    ['nama' => 'shared plate', 'jumlah' => 1],
                    ['nama' => 'achievement checklist', 'jumlah' => 1],
                    ['nama' => 'jam pasir', 'jumlah' => 1],
                    ['nama' => 'card', 'jumlah' => 60],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '48/FC/PK/2',
                'box' => 2,
                'lantai' => 2,
                'nama' => 'Fish Club',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Anak-anak',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://www.funlearning.co.uk/wp-content/uploads/2021/03/CLD0070-F1.jpg', 'https://m.media-amazon.com/images/I/71TEF1V53sL._AC_SL1500_.jpg'],
                'komponen' => [
                    ['nama' => 'akuarium', 'jumlah' => 1],
                    ['nama' => 'red fish', 'jumlah' => 9],
                    ['nama' => 'blue fish', 'jumlah' => 9],
                    ['nama' => 'seahorse', 'jumlah' => 4],
                    ['nama' => 'small fish', 'jumlah' => 4],
                    ['nama' => 'clam', 'jumlah' => 2],
                    ['nama' => 'starfish', 'jumlah' => 2],
                    ['nama' => 'sticker set', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '57/SM/PK/2',
                'box' => 2,
                'lantai' => 2,
                'nama' => 'Snack Match',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Party & Reaksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2022/12/SnackMatch-3DBox.jpg', 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/catalog-image/104/MTA-184823186/blue_orange_games_opened_-_snack_match_board_game_no_retur_-_d_full27_eypmtfz4.webp'],
                'komponen' => [
                    ['nama' => 'bahasa rules book', 'jumlah' => 6],
                    ['nama' => 'card (72 picnic card, 8 bonus card)', 'jumlah' => 80],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '59/WDI/PK/2',
                'box' => 2,
                'lantai' => 3,
                'nama' => 'Who Did It',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Deduksi & Party',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://image.astronauts.cloud/product-images/2024/2/HobbyIndonesiaWhoDidItBoardGame_4be4a486-a87a-458b-b0c0-07982a960f3b_900x900.png', 'https://static.lelekan.ua/image/cache/catalog/igri/hto-napudyv/hto_napudyv_01-800x800.jpg'],
                'komponen' => [
                    ['nama' => 'poop token', 'jumlah' => 13],
                    ['nama' => 'rules book', 'jumlah' => 8],
                    ['nama' => 'kartu', 'jumlah' => 36],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '1/CB/PK/3',
                'box' => 3,
                'lantai' => 1,
                'nama' => 'Cookie Box',
                'penerbit' => 'Korea Pavilion',
                'kategori' => 'Party',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://cf.geekdo-images.com/yf376XCJUCW_lvO3aS3h2w__imagepage/img/z61p-RfRYG7mlzKyPDPvGhfi-js=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3151052.jpg', 'https://cdn.svc.asmodee.net/production-asmodeeit/uploads/image-converter/2022/09/Cookie2-1024x1024.webp'],
                'komponen' => [
                    ['nama' => 'bel', 'jumlah' => 1],
                    ['nama' => 'kartu pesanan', 'jumlah' => 30],
                    ['nama' => 'cookies pesanan', 'jumlah' => 36],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '2/K/PK/3',
                'box' => 3,
                'lantai' => 2,
                'nama' => 'Kingdomino',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Strategi & Keluarga',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQByFMyOipn2ZuWjtKFiw0HRkWgjQYG2VliwM_z0NDHEw&s=10', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2M5M2NA2IThNtBdZiOB9bUeeZeawmO9OMIVmFoctuaEoE16ZGK-KuL7c&s=10'],
                'komponen' => [
                    ['nama' => 'domino', 'jumlah' => 48],
                    ['nama' => 'kartu persegi', 'jumlah' => 4],
                    ['nama' => 'bidak kayu', 'jumlah' => 8],
                    ['nama' => 'kastil karton', 'jumlah' => 4],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '8/TCGCP/PK/3',
                'box' => 3,
                'lantai' => 3,
                'nama' => 'Taco Cat Goat Cheese Pizza',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Party & Reaksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-8 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://m.media-amazon.com/images/I/81FaGDdNgnL.jpg', 'https://s3-ap-southeast-2.amazonaws.com/wc-prod-pim/JPEG_1000x1000/VR76954_C_taco_cat_goat_cheese_pizza_board_game.jpg'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 64],
                    ['nama' => 'panduan bermain', 'jumlah' => 2],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '10/GB/PK/3',
                'box' => 3,
                'lantai' => 1,
                'nama' => 'Geistes Blitz',
                'penerbit' => 'Amigo/Swan',
                'kategori' => 'Party & Reaksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-8 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://corners.ge/wp-content/uploads/2025/01/Geistesblitz-5-VOR-12.jpg', 'https://redcoast.myshopify.com/cdn/shop/products/product-image-1185587109_1010x.jpg?v=1575424250'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 60],
                    ['nama' => 'ornamen kursi', 'jumlah' => 1],
                    ['nama' => 'buku', 'jumlah' => 1],
                    ['nama' => 'tikus', 'jumlah' => 1],
                    ['nama' => 'botol', 'jumlah' => 1],
                    ['nama' => 'hantu', 'jumlah' => 1],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '19/S/PK/3',
                'box' => 3,
                'lantai' => 3,
                'nama' => 'Specific',
                'penerbit' => 'Gigamic',
                'kategori' => 'Kartu & Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://www.tcgpark.com/_next/image?url=https%3A%2F%2Fapi.tcgpark.com%2Fwp-content%2Fuploads%2F2023%2F08%2F3421273427450.jpg&w=3840&q=75', 'https://littlejordantoys.com/wp-content/uploads/2022/03/SPECIFIC1.jpg'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 28],
                    ['nama' => 'dadu', 'jumlah' => 3],
                    ['nama' => 'buku panduan bermain', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '26/ATN/PK/3',
                'box' => 3,
                'lantai' => 1,
                'nama' => 'Archaeology: The New Expedition',
                'penerbit' => 'Z-Man Games',
                'kategori' => 'Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-5 Pemain',
                'durasi' => '45 Menit',
                'link_foto' => ['https://cf.geekdo-images.com/GrPuR1uUv8ayILW3V6nTlg__imagepage/img/_yHRKeYowohBm6NQNhoWB5fXIa8=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5426071.jpg', 'https://monstergeekbg.com/cdn/shop/products/original_d843dd9a-9be4-4903-9073-ccdb35174d0f.jpg?v=1628521569'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 106],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                    ['nama' => 'monument tile', 'jumlah' => 6],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '30/P/PK/3',
                'box' => 3,
                'lantai' => 3,
                'nama' => 'Parade',
                'penerbit' => 'Z-Man Games',
                'kategori' => 'Kartu',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '30 Menit',
                'link_foto' => ['https://zatu.com/cdn/shop/files/ParadeParade-InsideParade-Back_grande.jpg?v=1760985071', 'https://mercular.s3.ap-southeast-1.amazonaws.com/images/products/2020/03/Parade-2.jpg'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 66],
                    ['nama' => 'panduan bermain', 'jumlah' => 1],
                    ['nama' => 'scorepad', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '32/PL/PK/3',
                'box' => 3,
                'lantai' => 2,
                'nama' => 'Project L',
                'penerbit' => 'Asmodee',
                'kategori' => 'Strategi Abstrak',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-4 Pemain',
                'durasi' => '20-40 Menit',
                'link_foto' => ['https://imgcdn.gamefound.com/extralarge/projects/2912/07548e99-3bb3-4163-b275-6402cf6183e5.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThqgwliUAsNxPsGvNgkEjJBGzmiiuVohAbvWoEFtMjfA&s=10'],
                'komponen' => [
                    ['nama' => 'puzzle putih', 'jumlah' => 32],
                    ['nama' => 'puzzle hitam', 'jumlah' => 20],
                    ['nama' => 'keping puzzle', 'jumlah' => 90],
                    ['nama' => 'alas pemain', 'jumlah' => 4],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '33/S/PK/3',
                'box' => 3,
                'lantai' => 3,
                'nama' => 'Scout',
                'penerbit' => 'Asmodee',
                'kategori' => 'Kartu',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '3-5 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://wobgames.net/wp-content/uploads/2022/05/scout-cardgame-japanese-english.webp', 'https://i.etsystatic.com/37518322/r/il/95ccfe/5164435942/il_fullxfull.5164435942_l0jf.jpg'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 45],
                    ['nama' => 'kartu uang', 'jumlah' => 23],
                    ['nama' => 'koin angka', 'jumlah' => 30],
                    ['nama' => 'koin mobil', 'jumlah' => 5],
                    ['nama' => 'koin segilima', 'jumlah' => 1],
                    ['nama' => 'buku panduan', 'jumlah' => 3],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '44/C/PK/3',
                'box' => 3,
                'lantai' => 2,
                'nama' => 'Cubessz',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Party & Dadu',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://cdn11.bigcommerce.com/s-15h1lhwmjz/images/stencil/1280x1280/products/1232/43853/f240fc1c-c166-4cd9-bcc8-7a6115525935__85244.1720411563.PNG?c=1', 'https://cdn11.bigcommerce.com/s-15h1lhwmjz/images/stencil/1280x1280/products/1232/43854/e32c6348-73ed-49f3-a1ef-1bb4a63d5834__20243.1720411562.PNG?c=1'],
                'komponen' => [
                    ['nama' => 'bahasa rules book', 'jumlah' => 8],
                    ['nama' => 'challenge card', 'jumlah' => 50],
                    ['nama' => 'dadu', 'jumlah' => 12],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '51/NSL/PK/3',
                'box' => 3,
                'lantai' => 2,
                'nama' => 'Next Station: London',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Strategi & Keluarga',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-4 Pemain',
                'durasi' => '15-20 Menit',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2021/12/NSL-Boite-scaled.png', 'https://i.etsystatic.com/42770788/r/il/9ed53c/7273554928/il_570xN.7273554928_sy3p.jpg'],
                'komponen' => [
                    ['nama' => 'pensil berwarna', 'jumlah' => 4],
                    ['nama' => 'kartu square', 'jumlah' => 9],
                    ['nama' => 'kartu biru', 'jumlah' => 6],
                    ['nama' => 'kartu merah muda', 'jumlah' => 5],
                    ['nama' => 'score sheet', 'jumlah' => 1],
                    ['nama' => 'panduan buku', 'jumlah' => 7],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '52/PD/PK/3',
                'box' => 3,
                'lantai' => 1,
                'nama' => 'Panic Diner',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Party & Kooperatif',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2019/04/PanicDiner-3DBox.jpg', 'https://veselosidim.ru/images/detailed/21/lifestyleltd-panic-diner-03.jpg'],
                'komponen' => [
                    ['nama' => 'papan permainan', 'jumlah' => 1],
                    ['nama' => 'mesin pencuci piring', 'jumlah' => 1],
                    ['nama' => 'token piring', 'jumlah' => 48],
                    ['nama' => 'token bintang', 'jumlah' => 15],
                    ['nama' => 'kartu pelanggan', 'jumlah' => 40],
                    ['nama' => 'timer 90 detik', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '58/V/PK/3',
                'box' => 3,
                'lantai' => 3,
                'nama' => 'Volto',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Party & Fisik',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://www.ludijeux.fr/cdn/shop/files/volto_decbb450-9dbe-4d19-a414-d2c87502467f_grande.jpg?v=1719912489', 'https://www.ludijeux.fr/cdn/shop/files/volto-p-image-83142-grande_1024x1024.jpg?v=1719912496'],
                'komponen' => [
                    ['nama' => 'rules book', 'jumlah' => 1],
                    ['nama' => 'mask', 'jumlah' => 20],
                    ['nama' => 'game mat', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '61/C/PK/3',
                'box' => 3,
                'lantai' => 2,
                'nama' => 'Celestia',
                'penerbit' => 'BRG/LBI',
                'kategori' => 'Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '45 Menit',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCLoOE42keWJuJV4z8CHx8ohsTbFg8sZTXqy123_R0FQ&s=10', 'https://i0.wp.com/opinionatedgamers.com/wp-content/uploads/2016/03/celestia.jpg?resize=454%2C386&ssl=1'],
                'komponen' => [
                    ['nama' => 'pesawat', 'jumlah' => 1],
                    ['nama' => 'bidak petualang', 'jumlah' => 6],
                    ['nama' => 'ubin petualang', 'jumlah' => 6],
                    ['nama' => 'ubin kota oval', 'jumlah' => 9],
                    ['nama' => 'dadu peristiwa', 'jumlah' => 4],
                    ['nama' => 'rulebook', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '13/RH/PK/4',
                'box' => 4,
                'lantai' => 3,
                'nama' => 'Rhino Hero',
                'penerbit' => 'Amigo/Swan',
                'kategori' => 'Anak & Ketangkasan',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-5 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://www.habausa.com/cdn/shop/files/games-rhino-hero-4789-1_720x.jpg?v=1698432047', 'https://m.media-amazon.com/images/I/81AIZostl1L.jpg'],
                'komponen' => [
                    ['nama' => 'rules', 'jumlah' => 1],
                    ['nama' => 'fondation', 'jumlah' => 1],
                    ['nama' => 'Rhino Hero', 'jumlah' => 1],
                    ['nama' => 'wall', 'jumlah' => 28],
                    ['nama' => 'cards', 'jumlah' => 31],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '14/SC/PK/4',
                'box' => 4,
                'lantai' => 2,
                'nama' => 'Speed Cups',
                'penerbit' => 'Amigo/Swan',
                'kategori' => 'Party & Reaksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://www.asdesjeux.com/cdn/shop/products/jeux-enfants-enfants-5-ans-speed-cups-2-fr-1173760705.jpg?v=1750837927', 'https://kassemstore.com/wp-content/uploads/2024/06/7299999082842-3.jpg'],
                'komponen' => [
                    ['nama' => 'picture card', 'jumlah' => 24],
                    ['nama' => 'cup (4 set warna)', 'jumlah' => 20],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '24/TN/PK/4',
                'box' => 4,
                'lantai' => 2,
                'nama' => 'The Number',
                'penerbit' => 'Repos Production',
                'kategori' => 'Party & Deduksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR_MKKyvSZhlR-xd9UA9GfpoXDuANPMIA47VflmvBWlxDmSurGvJIR3crBqkKMTKOr2mElcDW_c9csz1pZMHGIWqPmpq5pG_V4nX5lbFcCKiWyy57N-0MR6', 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQmeKhKwC7ha0-6wCx2iDo-JDJSJ4UwwcwiGexkxF84LvytGoywcad7ko0e_lYLirvkRJzFBA6Km-BXw1eH2gML_WypxQ0TiLBjzJV5BJlpCSWaHRgHx_MG1g'],
                'komponen' => [
                    ['nama' => 'papan pemain', 'jumlah' => 5],
                    ['nama' => 'ubin angka', 'jumlah' => 5],
                    ['nama' => 'spidol dry-erase', 'jumlah' => 5],
                    ['nama' => 'buku peraturan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '29/PB/PK/4',
                'box' => 4,
                'lantai' => 2,
                'nama' => 'Pandemic (Base)',
                'penerbit' => 'Z-Man Games',
                'kategori' => 'Kooperatif',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '45 Menit',
                'link_foto' => ['https://zatu.com/cdn/shop/files/Pandemic-2013.jpg?v=1760985299&width=843', 'https://static.gamesmen.com.au/media/catalog/product/cache/57ddbad6affa8d28869fa47188b75842/p/a/pandemic_board_game_4_.jpg'],
                'komponen' => [
                    ['nama' => 'role card', 'jumlah' => 7],
                    ['nama' => 'pawn', 'jumlah' => 7],
                    ['nama' => 'player card', 'jumlah' => 59],
                    ['nama' => 'reference card', 'jumlah' => 4],
                    ['nama' => 'infection card', 'jumlah' => 48],
                    ['nama' => 'research station', 'jumlah' => 6],
                    ['nama' => 'disease cube', 'jumlah' => 96],
                    ['nama' => 'board', 'jumlah' => 1],
                    ['nama' => 'rules book', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '46/DR/PK/4',
                'box' => 4,
                'lantai' => 3,
                'nama' => 'Doctor Rat',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Party',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://static.wixstatic.com/media/9b81af_b0fa4867680b49fdb609d644fcf12a7e~mv2.jpg/v1/fill/w_480,h_514,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/9b81af_b0fa4867680b49fdb609d644fcf12a7e~mv2.jpg', 'https://goblingames.mk/wp/wp-content/uploads/2023/12/Doctor-Rat1.jpg'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 129],
                    ['nama' => 'token aksi khusus', 'jumlah' => 5],
                    ['nama' => 'papan penghitung makanan', 'jumlah' => 1],
                    ['nama' => 'rat meeple', 'jumlah' => 1],
                    ['nama' => 'rules book', 'jumlah' => 2],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '55/SE/PK/4',
                'box' => 4,
                'lantai' => 1,
                'nama' => 'Sherlock Express',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Deduksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//110/MTA-38687546/blue_orange_blue_orange_sherlock_express_board_game_full04_ig6zo7ir.jpg', 'https://m.media-amazon.com/images/I/718y+HUHCgL.jpg'],
                'komponen' => [
                    ['nama' => 'suspect card', 'jumlah' => 27],
                    ['nama' => 'alibi card', 'jumlah' => 36],
                    ['nama' => 'illustrated rules 8 bahasa', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '60/WW/PK/4',
                'box' => 4,
                'lantai' => 2,
                'nama' => 'Wonder Woods',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Keluarga',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '20-30 Menit',
                'link_foto' => ['https://m.media-amazon.com/images/I/71QCU+cTkUL.jpg', 'https://www.bellalunatoys.com/cdn/shop/files/wonder-woods-mushroom-hunting-game-1_1800x1800.jpg?v=1721837851'],
                'komponen' => [
                    ['nama' => 'keranjang kayu', 'jumlah' => 35],
                    ['nama' => 'jamur kayu', 'jumlah' => 56],
                    ['nama' => 'token pemain pertama', 'jumlah' => 1],
                    ['nama' => 'papan lahan jamur', 'jumlah' => 4],
                    ['nama' => 'kartu informasi', 'jumlah' => 16],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '4/RF/PK/5',
                'box' => 5,
                'lantai' => 3,
                'nama' => 'Ramen Fury',
                'penerbit' => 'Mixlore',
                'kategori' => 'Party & Kartu',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '15-20 Menit',
                'link_foto' => ['https://image.astronauts.cloud/product-images/2024/1/RamenFuryBoardGame_1b9c47d7-eb58-41a7-a862-e48670871185_900x900.png', 'https://m.media-amazon.com/images/I/91izymg7STL._AC_UF894,1000_QL80_.jpg'],
                'komponen' => [
                    ['nama' => 'kartu mangkuk ramen', 'jumlah' => 15],
                    ['nama' => 'kartu bahan', 'jumlah' => 89],
                    ['nama' => 'token sendok', 'jumlah' => 10],
                    ['nama' => 'buku instruksi', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '6/S/PK/5',
                'box' => 5,
                'lantai' => 2,
                'nama' => 'Sequence',
                'penerbit' => 'Goliath Games',
                'kategori' => 'Keluarga & Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-12 Pemain',
                'durasi' => '30 Menit',
                'link_foto' => ['https://m.media-amazon.com/images/I/816K0RyrhzL._SL1500_.jpg', 'https://m.media-amazon.com/images/I/81RzQEc0GTL._SL1500_.jpg'],
                'komponen' => [
                    ['nama' => 'instruction card', 'jumlah' => 1],
                    ['nama' => 'game board', 'jumlah' => 1],
                    ['nama' => 'kartu main', 'jumlah' => 104],
                    ['nama' => 'marker chip', 'jumlah' => 135],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '7/SIEB/PK/5',
                'box' => 5,
                'lantai' => 2,
                'nama' => 'Spot It (Eco Blister/Peg)',
                'penerbit' => 'Zygomatic',
                'kategori' => 'Party & Reaksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-8 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDxhUT45Pm0bh1tDMnkd40SUeqZD3FhOoCBx6AO-JULWagzV1car-NW8OK&s=10', 'https://store.asmodee.com/cdn/shop/files/SPR103ML-image5_2000_535x.jpg?v=1721231097'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 55],
                    ['nama' => 'kaleng', 'jumlah' => 1],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                    ['nama' => 'mini game', 'jumlah' => 5],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '11/GB/PK/5',
                'box' => 5,
                'lantai' => 3,
                'nama' => 'Get Bit',
                'penerbit' => 'Amigo/Swan',
                'kategori' => 'Party',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://m.media-amazon.com/images/I/71lJtqKqgdL.jpg_BO30,255,255,255_UF750,750_SR1910,1000,0,C_QL100_.jpg', 'https://shop.greaterthangames.com/cdn/shop/files/GBIT-CORE-2.jpg?v=1761761857&2000w'],
                'komponen' => [
                    ['nama' => 'figure', 'jumlah' => 6],
                    ['nama' => 'hungry shark', 'jumlah' => 1],
                    ['nama' => 'panduan bermain', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '22/RL/PK/5',
                'box' => 5,
                'lantai' => 1,
                'nama' => 'Rustling Leaves',
                'penerbit' => 'Kosmos',
                'kategori' => 'Strategi Ringan',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2 Pemain',
                'durasi' => '20 Menit',
                'link_foto' => ['https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//97/MTA-38026607/kosmos_rustling_leaves_board_game_full01_rbn7p20a.jpg', 'https://zatu.com/cdn/shop/files/Rustling-Leaves-1-3.jpg?v=1760982213&width=500'],
                'komponen' => [
                    ['nama' => 'lembar skor', 'jumlah' => 1],
                    ['nama' => 'dadu', 'jumlah' => 2],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '34/TE/PK/5',
                'box' => 5,
                'lantai' => 3,
                'nama' => 'Timeline Events',
                'penerbit' => null,
                'kategori' => 'Edukasi & Kartu',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-8 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://www.boardgamebliss.com/cdn/shop/products/TIMEECO02EN_1-B.jpg?crop=center&height=1200&v=1611942227&width=1200', 'https://www.gaminglib.com/cdn/shop/products/timeline-events-eco-blister-815651.jpg?v=1702904258'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 55],
                    ['nama' => 'kaleng', 'jumlah' => 1],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '35/TI/PK/5',
                'box' => 5,
                'lantai' => 3,
                'nama' => 'Timeline Inventions',
                'penerbit' => 'Asmodee',
                'kategori' => 'Edukasi & Kartu',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-8 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://cdn.svc.asmodee.net/production-asmodeeit/uploads/2022/09/timeline_invenzioni.png', 'https://www.zygomatic-games.com/wp-content/uploads/2019/08/zigomatic-timeline-inventions-02.jpg'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 55],
                    ['nama' => 'kaleng', 'jumlah' => 1],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '36/WP/PK/5',
                'box' => 5,
                'lantai' => 1,
                'nama' => 'Wrong Party',
                'penerbit' => 'Unstable Games',
                'kategori' => 'Party',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '3-10 Pemain',
                'durasi' => '30-45 Menit',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNt4_h-pnpT7-XzsCTh2Mfa5CjCAO1rDHn0F2F9RP_9GyfQ659GjlPkMw&s=10', 'https://m.media-amazon.com/images/I/51-3NTjj3JL._SX522_.jpg'],
                'komponen' => [
                    ['nama' => 'panduan buku', 'jumlah' => 1],
                    ['nama' => 'kartu', 'jumlah' => 152],
                    ['nama' => 'topi party', 'jumlah' => 5],
                    ['nama' => 'score tracker', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '47/DENV/PK/5',
                'box' => 5,
                'lantai' => 2,
                'nama' => 'Dr. Eureka New Version',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Party & Kecepatan',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://image.astronauts.cloud/product-images/2024/2/HobbyIndonesiaDr_da195624-bc11-4b12-9171-fe92ad2ee9ec_900x900.jpg', 'https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full/catalog-image/106/MTA-167884170/brd-24346_mainan-anak-dr-eureka-board-game_full01-664a62f7.jpg'],
                'komponen' => [
                    ['nama' => 'buku panduan bermain', 'jumlah' => 8],
                    ['nama' => 'kartu', 'jumlah' => 54],
                    ['nama' => 'bola hijau', 'jumlah' => 8],
                    ['nama' => 'bola ungu', 'jumlah' => 8],
                    ['nama' => 'bola merah', 'jumlah' => 8],
                    ['nama' => 'tabung akrilik', 'jumlah' => 12],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '50/MR/PK/5',
                'box' => 5,
                'lantai' => 2,
                'nama' => 'Moon River',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '45-60 Menit',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2023/07/MoonRiver-3DBox.jpg', 'https://www.toysoupcanada.com/cdn/shop/files/moonriver2_1200x1200.jpg?v=1743438935'],
                'komponen' => [
                    ['nama' => 'papan reservasi', 'jumlah' => 4],
                    ['nama' => 'meeple ranchero', 'jumlah' => 8],
                    ['nama' => 'petak lahan', 'jumlah' => 96],
                    ['nama' => 'token mitra', 'jumlah' => 20],
                    ['nama' => 'meeple sapi', 'jumlah' => 32],
                    ['nama' => 'papan saloon', 'jumlah' => 1],
                    ['nama' => 'score pad', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '53/PJ/PK/5',
                'box' => 5,
                'lantai' => 1,
                'nama' => 'Pengo Jump',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Anak-anak',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://www.static-src.com/wcsstore/Indraprastha/images/catalog/full//catalog-image/119/MTA-95756978/pen_pengo_jump_board_game_full06_p5265j4r.jpeg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTNwp0YxoeMeKdUZ1FFmdAnsV9ln4V8Z0CPUJs0iiDLQ&s'],
                'komponen' => [
                    ['nama' => 'rules book', 'jumlah' => 1],
                    ['nama' => 'sea board', 'jumlah' => 1],
                    ['nama' => 'penguin', 'jumlah' => 4],
                    ['nama' => 'bag', 'jumlah' => 1],
                    ['nama' => 'salju', 'jumlah' => 18],
                    ['nama' => 'frosty tile', 'jumlah' => 6],
                    ['nama' => 'sea lion beku', 'jumlah' => 6],
                    ['nama' => 'sea lion', 'jumlah' => 12],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '5/RA/PK/6',
                'box' => 6,
                'lantai' => 2,
                'nama' => 'Resistance: Avalon',
                'penerbit' => 'Indie Boards & Cards',
                'kategori' => 'Sosial Deduksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '5-10 Pemain',
                'durasi' => '30 Menit',
                'link_foto' => ['https://down-id.img.susercontent.com/file/0ef3194c3fb606b4ff03cdc4dff7b48e', 'https://down-id.img.susercontent.com/file/f007f8e1ef1d0d2a5e0a635958bba5f8.webp'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 26],
                    ['nama' => 'karton kecil', 'jumlah' => 25],
                    ['nama' => 'karton besar', 'jumlah' => 1],
                    ['nama' => 'koin besar', 'jumlah' => 5],
                    ['nama' => 'koin kecil', 'jumlah' => 2],
                    ['nama' => 'lembar tabel vote', 'jumlah' => 3],
                    ['nama' => 'panduan bermain', 'jumlah' => 2],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '12/HG/PK/6',
                'box' => 6,
                'lantai' => 3,
                'nama' => 'Halli Galli',
                'penerbit' => 'Amigo/Swan',
                'kategori' => 'Party & Reaksi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-6 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://images.thimbletoys.com/images/items/2030032a1.jpg', 'https://down-id.img.susercontent.com/file/id-11134207-7qukz-lglw98njx4e7d4'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 56],
                    ['nama' => 'bell', 'jumlah' => 1],
                    ['nama' => 'panduan bermain', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '27/C/PK/6',
                'box' => 6,
                'lantai' => 3,
                'nama' => 'Carcassonne',
                'penerbit' => 'Z-Man Games',
                'kategori' => 'Strategi & Keluarga',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-5 Pemain',
                'durasi' => '35-45 Menit',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvgzX1Nt9MkUIJ8FxZp9UFlmSnZA5XxOv6gehGzkVnM1TXXXCUM_NhvMne&s=10', 'https://i.ebayimg.com/images/g/fnUAAeSwwWFpL2yr/s-l1200.jpg'],
                'komponen' => [
                    ['nama' => 'ubin permainan', 'jumlah' => 84],
                    ['nama' => 'papan bermain', 'jumlah' => 1],
                    ['nama' => 'bidak kayu', 'jumlah' => 45],
                    ['nama' => 'lembar panduan bermain', 'jumlah' => 2],
                    ['nama' => 'brosur game', 'jumlah' => 2],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '37/UM/PK/6',
                'box' => 6,
                'lantai' => 1,
                'nama' => 'UNLOCK! Mystery Adventures',
                'penerbit' => 'Space Cowboys',
                'kategori' => 'Kooperatif & Escape Room',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-6 Pemain',
                'durasi' => '60 Menit',
                'link_foto' => ['https://down-id.img.susercontent.com/file/1e7e8add80b8ab36f49d601df6b9e136', 'https://down-id.img.susercontent.com/file/e6a033c5aaf00e79aaf300fe70a43dd7'],
                'komponen' => [
                    ['nama' => 'petualangan (186 kartu)', 'jumlah' => 3],
                    ['nama' => 'kartu tutorial', 'jumlah' => 10],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '38/UT/PK/6',
                'box' => 6,
                'lantai' => 3,
                'nama' => 'UNLOCK! Timeless Adventures',
                'penerbit' => 'Space Cowboys',
                'kategori' => 'Kooperatif & Escape Room',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-6 Pemain',
                'durasi' => '60 Menit',
                'link_foto' => ['https://store.asmodee.com/cdn/shop/products/UNL06-image1_2000_400x@2x.jpg?v=1760644366', 'https://store.asmodee.com/cdn/shop/products/UNL06-image3_2000_400x@2x.jpg?v=1690580048'],
                'komponen' => [
                    ['nama' => 'kartu tutorial', 'jumlah' => 10],
                    ['nama' => 'petualangan (180 kartu + 3 lembar kertas)', 'jumlah' => 3],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '39/USW/PK/6',
                'box' => 6,
                'lantai' => 1,
                'nama' => 'UNLOCK! Star Wars Adventures',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Kooperatif & Escape Room',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-6 Pemain',
                'durasi' => '60 Menit',
                'link_foto' => ['https://www.m-g.com.au/wp-content/uploads/2022/08/3558380073277_SWU001_Unlock_Star_Wars.jpg', 'https://www.m-g.com.au/wp-content/uploads/2022/08/3558380073277_SWU001_Unlock_Star_Wars_3.jpg'],
                'komponen' => [
                    ['nama' => 'petualangan (180 kartu)', 'jumlah' => 3],
                    ['nama' => 'booklet', 'jumlah' => 1],
                    ['nama' => 'peta', 'jumlah' => 1],
                    ['nama' => 'kartu tutorial', 'jumlah' => 10],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '40/S/PK/6',
                'box' => 6,
                'lantai' => 1,
                'nama' => 'Spellbook',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Strategi & Kartu',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2-4 Pemain',
                'durasi' => '30-45 Menit',
                'link_foto' => ['https://down-id.img.susercontent.com/file/id-11134207-7r98s-llvosfyte4jwb9', 'https://www.miniaturemarket.com/media/01/54/ef/1752295810/scspel01en-2.jpg'],
                'komponen' => [
                    ['nama' => 'rule book', 'jumlah' => 1],
                    ['nama' => 'pouch', 'jumlah' => 1],
                    ['nama' => 'altar', 'jumlah' => 1],
                    ['nama' => 'discard box', 'jumlah' => 1],
                    ['nama' => 'familiar board', 'jumlah' => 4],
                    ['nama' => 'player aid card', 'jumlah' => 4],
                    ['nama' => 'spell card', 'jumlah' => 84],
                    ['nama' => 'materia token', 'jumlah' => 105],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '21/P/PK/7',
                'box' => 7,
                'lantai' => 1,
                'nama' => 'Polis',
                'penerbit' => 'Kosmos',
                'kategori' => 'Strategi Ekonomi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-2 Pemain',
                'durasi' => '30-45 Menit',
                'link_foto' => ['https://i5.walmartimages.com/asr/7b7bdd89-9e1b-4b39-96fa-ad5000cc45b9.6f5722639397c21db57a1d605e9f13ab.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF', 'https://m.media-amazon.com/images/I/61Ry6ZtA1+L.jpg'],
                'komponen' => [
                    ['nama' => 'papan utama', 'jumlah' => 1],
                    ['nama' => 'papan pribadi', 'jumlah' => 2],
                    ['nama' => 'lembar informasi pemain', 'jumlah' => 2],
                    ['nama' => 'dadu 4 sisi', 'jumlah' => 1],
                    ['nama' => 'buah kayu', 'jumlah' => 168],
                    ['nama' => 'ubin proyek', 'jumlah' => 14],
                    ['nama' => 'kartu', 'jumlah' => 90],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '25/A/PK/7',
                'box' => 7,
                'lantai' => 1,
                'nama' => 'Atiwa',
                'penerbit' => 'Lookout Games',
                'kategori' => 'Strategi',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-4 Pemain',
                'durasi' => '60-90 Menit',
                'link_foto' => ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSah1Dg3nLDaLPyG4kVSJZ2x9szCyVf3kDrLQzyhCiyQg&s=10', 'https://ugi-games.com/wp-content/uploads/2022/07/14648-lookout-games-atiwa-juego-mesa-espanol-2.jpg'],
                'komponen' => [
                    ['nama' => 'booklet', 'jumlah' => 1],
                    ['nama' => 'rule book', 'jumlah' => 1],
                    ['nama' => 'action board', 'jumlah' => 1],
                    ['nama' => 'supply board', 'jumlah' => 4],
                    ['nama' => 'pohon token', 'jumlah' => 52],
                    ['nama' => 'family token', 'jumlah' => 52],
                    ['nama' => 'kartu', 'jumlah' => 88],
                    ['nama' => 'wooden piece', 'jumlah' => 200],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '31/CB/PK/7',
                'box' => 7,
                'lantai' => 3,
                'nama' => 'Catan (Base)',
                'penerbit' => 'Catan Studio',
                'kategori' => 'Strategi & Keluarga',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '3-4 Pemain',
                'durasi' => '60-120 Menit',
                'link_foto' => ['https://catanshop.com/images/thumbs/0002217_catan-zip_600.jpeg', 'https://www.game.co.uk/images/imgzoom/89/89028999_xxl_a2.jpg'],
                'komponen' => [
                    ['nama' => 'kartu', 'jumlah' => 120],
                    ['nama' => 'karton hexagonal', 'jumlah' => 19],
                    ['nama' => 'karton border', 'jumlah' => 6],
                    ['nama' => 'dadu', 'jumlah' => 2],
                    ['nama' => 'koin karton', 'jumlah' => 24],
                    ['nama' => 'rumah kayu', 'jumlah' => 36],
                    ['nama' => 'kayu balok', 'jumlah' => 60],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '43/B/PK/7',
                'box' => 7,
                'lantai' => 1,
                'nama' => 'Brix',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Strategi Abstrak',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '2 Pemain',
                'durasi' => '15 Menit',
                'link_foto' => ['https://blueorangegames.eu/wp-content/uploads/2018/06/Brix-3DBox.jpg', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-dIxs62ihpepJPG3ox7qjg4E8qxkD5gBWG113dYxGWl3bWDeW4VsOITo&s=10'],
                'komponen' => [
                    ['nama' => 'bricks', 'jumlah' => 22],
                    ['nama' => 'rulebook', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
            [
                'kode' => '56/SQ/PK/7',
                'box' => 7,
                'lantai' => 1,
                'nama' => 'Slide Quest',
                'penerbit' => 'Blue Orange Games',
                'kategori' => 'Keluarga & Ketangkasan',
                'jumlah' => 1,
                'available_copies' => 1,
                'satuan' => 'set',
                'tingkat_kesulitan' => null,
                'usia_minimum' => null,
                'jumlah_pemain' => '1-4 Pemain',
                'durasi' => '20-30 Menit',
                'link_foto' => ['https://www.okkazeo.com/images/jeux/28171.jpg', 'https://down-id.img.susercontent.com/file/1dc611cd381c033cdc746ccef2b2b0ae'],
                'komponen' => [
                    ['nama' => 'papan dengan perangkap', 'jumlah' => 1],
                    ['nama' => 'tuas', 'jumlah' => 4],
                    ['nama' => 'peta', 'jumlah' => 20],
                    ['nama' => 'ksatria bergulir', 'jumlah' => 1],
                    ['nama' => 'rintangan', 'jumlah' => 8],
                    ['nama' => 'perangkap', 'jumlah' => 9],
                    ['nama' => 'buku panduan', 'jumlah' => 1],
                ],
                'barang_hilang' => null,
                'populer' => false,
            ],
        ];

        foreach ($games as $game) {
            BoardGame::updateOrCreate(['kode' => $game['kode']], $game);
        }
    }
}