<?php

namespace Database\Seeders;

use App\Models\BoardGame;
use Illuminate\Database\Seeder;

class BoardGameSeeder extends Seeder
{
    public function run(): void
    {
        $games = [
            ['kode' => '18/Y/PK/1', 'box' => 'Box 1', 'lantai' => 3, 'nama' => 'Yak', 'penerbit' => 'Plan B Games', 'jumlah' => 1, 'deskripsi_isi' => '1 rulebook, 1 punchboard, 1 game board, 1 bag, 1 score pad, 1 baby yak, 4 yak besar, 4 keranjang, 4 player board, 1 mountain, 1 stupa marker, 1 awan, 8 carts panel, 8 roda, 5 fogs, 45 food token, 20 cards, 8 batu kristal, 64 batu warna, 8 tanduk putih.', 'kategori' => 'Strategi', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '60-90 Menit', 'status' => 'tersedia'],
            ['kode' => '20/I/PK/1', 'box' => 'Box 1', 'lantai' => 2, 'nama' => 'Imhotep', 'penerbit' => 'Kosmos', 'jumlah' => 1, 'deskripsi_isi' => '120 wooden cubes, 5 site boards, 1 scoring track, 8 ship tokens, 4 supply sled tokens, 21 round cards, 34 market cards, 1 rule booklet.', 'kategori' => 'Strategi', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '40 Menit', 'status' => 'tersedia'],
            ['kode' => '23/U/PK/1', 'box' => 'Box 1', 'lantai' => 1, 'nama' => 'Ubongo', 'penerbit' => 'Kosmos', 'jumlah' => 1, 'deskripsi_isi' => '4x12 ubin, 36 papan puzzle, 1 dadu, 1 jam pasir, 1 kantong kain, 1 trek ronde, 58 permata (19 safir, 19 amber, 10 rubi, 10 zamrud).', 'kategori' => 'Puzzle', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '35 Menit', 'status' => 'tersedia'],
            ['kode' => '28/1830RRB/PK/1', 'box' => 'Box 1', 'lantai' => 1, 'nama' => '1830: Railways & Robber Barons', 'penerbit' => 'Look Out Games', 'jumlah' => 1, 'deskripsi_isi' => '1 papan permainan dua sisi, 117 kartu, 8 piagam perusahaan, 1 tumpukan uang, 85 ubin heksagonal, 25 token lingkaran, 25 penanda persegi, 1 rulebook.', 'kategori' => 'Strategi Ekonomi', 'jumlah_pemain' => '2-7 Pemain', 'durasi' => '180-300 Menit', 'status' => 'tersedia'],
            ['kode' => '42/BN/PK/1', 'box' => 'Box 1', 'lantai' => 1, 'nama' => 'Block Ness', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 papan Loch, 4 monster warna berbeda (masing-masing 12 bagian), buku aturan 8 bahasa.', 'kategori' => 'Keluarga', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '49/ML/PK/1', 'box' => 'Box 1', 'lantai' => 1, 'nama' => 'Meeple Land', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '4 papan Plot, 1 papan Parking Lot, 4 ubin Plot Extension, 101 ubin Attraction/Service, 17 ubin Bus, 124 Meeple Pengunjung, 52 koin, rules book 7 bahasa.', 'kategori' => 'Manajemen', 'jumlah_pemain' => '1-4 Pemain', 'durasi' => '20-40 Menit', 'status' => 'tersedia'],
            ['kode' => '54/P/PK/1', 'box' => 'Box 1', 'lantai' => 2, 'nama' => 'Photosynthesis', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 papan permainan, 1 segmen matahari, 4 papan pemain, 24 token biji, 32 pohon kecil, 16 pohon sedang, 8 pohon besar, aturan bergambar.', 'kategori' => 'Strategi', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '60-90 Menit', 'status' => 'tersedia'],
            ['kode' => '3/P/PK/2', 'box' => 'Box 2', 'lantai' => 2, 'nama' => 'Pengoloo', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '12 penguin, 12 telur (6 warna), 1 rules book, 4 score board, 2 dadu.', 'kategori' => 'Anak & Memori', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '9/TO/PK/2', 'box' => 'Box 2', 'lantai' => 3, 'nama' => 'Tongues Out', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '12 dogs, 1 rules book, 4 kartu, 2 dadu.', 'kategori' => 'Party & Reaksi', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '15/TM/PK/2', 'box' => 'Box 2', 'lantai' => 3, 'nama' => 'The Mind', 'penerbit' => 'Amigo/Swan', 'jumlah' => 1, 'deskripsi_isi' => '120 kartu, 1 panduan bermain.', 'kategori' => 'Kooperatif', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '20 Menit', 'status' => 'dipinjam'],
            ['kode' => '16/TN7/PK/2', 'box' => 'Box 2', 'lantai' => 1, 'nama' => 'The Nasty 7', 'penerbit' => 'Amigo/Swan', 'jumlah' => 1, 'deskripsi_isi' => '110 kartu, 1 panduan bermain.', 'kategori' => 'Kartu', 'jumlah_pemain' => '3-6 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '17/ASGOS/PK/2', 'box' => 'Box 2', 'lantai' => 1, 'nama' => 'Azul: Stained Glass of Sintra', 'penerbit' => 'Plan B Games', 'jumlah' => 1, 'deskripsi_isi' => '9 factory display, 4 palace board, 32 pattern strip, 4 glazier, 100 pane piece, 1 scoring board, 1 glass tower, 1 bag, 1 rulebook.', 'kategori' => 'Strategi Abstrak', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '30-45 Menit', 'status' => 'dipinjam'],
            ['kode' => '41/B/PK/2', 'box' => 'Box 2', 'lantai' => 2, 'nama' => 'Bendomino', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 rule book, 28 domino.', 'kategori' => 'Keluarga', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '45/CA/PK/2', 'box' => 'Box 2', 'lantai' => 3, 'nama' => 'Cupcake Academy', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '8 bahasa rules book, 20 cupcake cups, 12 plate, 1 shared plate, 1 achievement checklist, 1 jam pasir, 60 card.', 'kategori' => 'Anak & Keluarga', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15-20 Menit', 'status' => 'tersedia'],
            ['kode' => '48/FC/PK/2', 'box' => 'Box 2', 'lantai' => 2, 'nama' => 'Fish Club', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 akuarium, 9 red fish, 9 blue fish, 4 seahorse, 4 small fish, 2 clam, 2 starfish, 1 sticker set.', 'kategori' => 'Anak-anak', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '57/SM/PK/2', 'box' => 'Box 2', 'lantai' => 2, 'nama' => 'Snack Match', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '6 bahasa rules book, 80 card (72 picnic card, 8 bonus card).', 'kategori' => 'Party & Reaksi', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '59/WDI/PK/2', 'box' => 'Box 2', 'lantai' => 3, 'nama' => 'Who Did It', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '13 poop token, 8 rules book, 36 kartu.', 'kategori' => 'Deduksi & Party', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '1/CB/PK/3', 'box' => 'Box 3', 'lantai' => 1, 'nama' => 'Cookie Box', 'penerbit' => 'Korea Pavilion', 'jumlah' => 1, 'deskripsi_isi' => '1 bel, 30 kartu pesanan, 36 cookies pesanan.', 'kategori' => 'Party', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '2/K/PK/3', 'box' => 'Box 3', 'lantai' => 2, 'nama' => 'Kingdomino', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '48 domino, 4 kartu persegi, 8 bidak kayu, 4 kastil karton, 1 buku panduan.', 'kategori' => 'Strategi & Keluarga', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '20 Menit', 'status' => 'dipinjam'],
            ['kode' => '8/TCGCP/PK/3', 'box' => 'Box 3', 'lantai' => 3, 'nama' => 'Taco Cat Goat Cheese Pizza', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '64 kartu, 2 panduan bermain.', 'kategori' => 'Party & Reaksi', 'jumlah_pemain' => '2-8 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '10/GB/PK/3', 'box' => 'Box 3', 'lantai' => 1, 'nama' => 'Geistes Blitz', 'penerbit' => 'Amigo/Swan', 'jumlah' => 1, 'deskripsi_isi' => '60 kartu, ornamen kursi, buku, tikus, botol, hantu, 1 buku panduan.', 'kategori' => 'Party & Reaksi', 'jumlah_pemain' => '2-8 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '19/S/PK/3', 'box' => 'Box 3', 'lantai' => 3, 'nama' => 'Specific', 'penerbit' => 'Gigamic', 'jumlah' => 1, 'deskripsi_isi' => '28 kartu, 3 dadu, 1 buku panduan bermain.', 'kategori' => 'Kartu & Strategi', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '26/ATN/PK/3', 'box' => 'Box 3', 'lantai' => 1, 'nama' => 'Archaeology: The New Expedition', 'penerbit' => 'Z-Man Games', 'jumlah' => 1, 'deskripsi_isi' => '106 kartu, 1 buku panduan, 6 monument tile.', 'kategori' => 'Strategi', 'jumlah_pemain' => '2-5 Pemain', 'durasi' => '45 Menit', 'status' => 'tersedia'],
            ['kode' => '30/P/PK/3', 'box' => 'Box 3', 'lantai' => 3, 'nama' => 'Parade', 'penerbit' => 'Z-Man Games', 'jumlah' => 1, 'deskripsi_isi' => '66 kartu, 1 panduan bermain, 1 scorepad.', 'kategori' => 'Kartu', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '30 Menit', 'status' => 'tersedia'],
            ['kode' => '32/PL/PK/3', 'box' => 'Box 3', 'lantai' => 2, 'nama' => 'Project L', 'penerbit' => 'Asmodee', 'jumlah' => 1, 'deskripsi_isi' => '32 puzzle putih, 20 puzzle hitam, 90 keping puzzle, 4 alas pemain.', 'kategori' => 'Strategi Abstrak', 'jumlah_pemain' => '1-4 Pemain', 'durasi' => '20-40 Menit', 'status' => 'tersedia'],
            ['kode' => '33/S/PK/3', 'box' => 'Box 3', 'lantai' => 3, 'nama' => 'Scout', 'penerbit' => 'Asmodee', 'jumlah' => 1, 'deskripsi_isi' => '45 kartu, 23 kartu uang, 30 koin angka, 5 koin mobil, 1 koin segilima, 3 buku panduan.', 'kategori' => 'Kartu', 'jumlah_pemain' => '3-5 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '44/C/PK/3', 'box' => 'Box 3', 'lantai' => 2, 'nama' => 'Cubessz', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '8 bahasa rules book, 50 challenge card, 12 dadu.', 'kategori' => 'Party & Dadu', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '51/NSL/PK/3', 'box' => 'Box 3', 'lantai' => 2, 'nama' => 'Next Station: London', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '4 pensil berwarna, 9 kartu square, 6 kartu biru, 5 kartu merah muda, score sheet, 7 panduan buku.', 'kategori' => 'Strategi & Keluarga', 'jumlah_pemain' => '1-4 Pemain', 'durasi' => '15-20 Menit', 'status' => 'tersedia'],
            ['kode' => '52/PD/PK/3', 'box' => 'Box 3', 'lantai' => 1, 'nama' => 'Panic Diner', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 papan permainan, 1 mesin pencuci piring, 48 token piring, 15 token bintang, 40 kartu pelanggan, 1 timer 90 detik.', 'kategori' => 'Party & Kooperatif', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '58/V/PK/3', 'box' => 'Box 3', 'lantai' => 3, 'nama' => 'Volto', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 rules book, 20 mask, 1 game mat.', 'kategori' => 'Party & Fisik', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '61/C/PK/3', 'box' => 'Box 3', 'lantai' => 2, 'nama' => 'Celestia', 'penerbit' => 'BRG/LBI', 'jumlah' => 1, 'deskripsi_isi' => '1 pesawat, 6 bidak petualang, 6 ubin petualang, 9 ubin kota oval, 4 dadu peristiwa, 1 rulebook.', 'kategori' => 'Strategi', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '45 Menit', 'status' => 'tersedia'],
            ['kode' => '13/RH/PK/4', 'box' => 'Box 4', 'lantai' => 3, 'nama' => 'Rhino Hero', 'penerbit' => 'Amigo/Swan', 'jumlah' => 1, 'deskripsi_isi' => '1 rules, 1 fondation, 1 Rhino Hero, 28 wall, 31 cards.', 'kategori' => 'Anak & Ketangkasan', 'jumlah_pemain' => '2-5 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '14/SC/PK/4', 'box' => 'Box 4', 'lantai' => 2, 'nama' => 'Speed Cups', 'penerbit' => 'Amigo/Swan', 'jumlah' => 1, 'deskripsi_isi' => '24 picture card, 20 cup (4 set warna).', 'kategori' => 'Party & Reaksi', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '24/TN/PK/4', 'box' => 'Box 4', 'lantai' => 2, 'nama' => 'The Number', 'penerbit' => 'Repos Production', 'jumlah' => 1, 'deskripsi_isi' => '5 papan pemain, 5 ubin angka, 5 spidol dry-erase, 1 buku peraturan.', 'kategori' => 'Party & Deduksi', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '29/PB/PK/4', 'box' => 'Box 4', 'lantai' => 2, 'nama' => 'Pandemic (Base)', 'penerbit' => 'Z-Man Games', 'jumlah' => 1, 'deskripsi_isi' => '7 role card, 7 pawn, 59 player card, 4 reference card, 48 infection card, 6 research station, 96 disease cube, 1 board, 1 rules book.', 'kategori' => 'Kooperatif', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '45 Menit', 'status' => 'dipinjam'],
            ['kode' => '46/DR/PK/4', 'box' => 'Box 4', 'lantai' => 3, 'nama' => 'Doctor Rat', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '129 kartu, 5 token aksi khusus, 1 papan penghitung makanan, 1 rat meeple, 2 rules book.', 'kategori' => 'Party', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '55/SE/PK/4', 'box' => 'Box 4', 'lantai' => 1, 'nama' => 'Sherlock Express', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '27 suspect card, 36 alibi card, illustrated rules 8 bahasa.', 'kategori' => 'Deduksi', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '60/WW/PK/4', 'box' => 'Box 4', 'lantai' => 2, 'nama' => 'Wonder Woods', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '35 keranjang kayu, 56 jamur kayu, 1 token pemain pertama, 4 papan lahan jamur, 16 kartu informasi.', 'kategori' => 'Keluarga', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '20-30 Menit', 'status' => 'dipinjam'],
            ['kode' => '4/RF/PK/5', 'box' => 'Box 5', 'lantai' => 3, 'nama' => 'Ramen Fury', 'penerbit' => 'Mixlore', 'jumlah' => 1, 'deskripsi_isi' => '15 kartu mangkuk ramen, 89 kartu bahan, 10 token sendok, 1 buku instruksi.', 'kategori' => 'Party & Kartu', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '15-20 Menit', 'status' => 'tersedia'],
            ['kode' => '6/S/PK/5', 'box' => 'Box 5', 'lantai' => 2, 'nama' => 'Sequence', 'penerbit' => 'Goliath Games', 'jumlah' => 1, 'deskripsi_isi' => '1 instruction card, 1 game board, 104 kartu main, 135 marker chip.', 'kategori' => 'Keluarga & Strategi', 'jumlah_pemain' => '2-12 Pemain', 'durasi' => '30 Menit', 'status' => 'dipinjam'],
            ['kode' => '7/SIEB/PK/5', 'box' => 'Box 5', 'lantai' => 2, 'nama' => 'Spot It (Eco Blister/Peg)', 'penerbit' => 'Zygomatic', 'jumlah' => 1, 'deskripsi_isi' => '55 kartu, 1 kaleng, 1 buku panduan, 5 mini game.', 'kategori' => 'Party & Reaksi', 'jumlah_pemain' => '2-8 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '11/GB/PK/5', 'box' => 'Box 5', 'lantai' => 3, 'nama' => 'Get Bit', 'penerbit' => 'Amigo/Swan', 'jumlah' => 1, 'deskripsi_isi' => '6 figure, 1 hungry shark, 1 panduan bermain.', 'kategori' => 'Party', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '22/RL/PK/5', 'box' => 'Box 5', 'lantai' => 1, 'nama' => 'Rustling Leaves', 'penerbit' => 'Kosmos', 'jumlah' => 1, 'deskripsi_isi' => '1 lembar skor, 2 dadu, 1 buku panduan.', 'kategori' => 'Strategi Ringan', 'jumlah_pemain' => '2 Pemain', 'durasi' => '20 Menit', 'status' => 'tersedia'],
            ['kode' => '34/TE/PK/5', 'box' => 'Box 5', 'lantai' => 3, 'nama' => 'Timeline Events', 'penerbit' => '-', 'jumlah' => 1, 'deskripsi_isi' => '55 kartu, 1 kaleng, 1 buku panduan.', 'kategori' => 'Edukasi & Kartu', 'jumlah_pemain' => '2-8 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '35/TI/PK/5', 'box' => 'Box 5', 'lantai' => 3, 'nama' => 'Timeline Inventions', 'penerbit' => 'Asmodee', 'jumlah' => 1, 'deskripsi_isi' => '55 kartu, 1 kaleng, 1 buku panduan.', 'kategori' => 'Edukasi & Kartu', 'jumlah_pemain' => '2-8 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '36/WP/PK/5', 'box' => 'Box 5', 'lantai' => 1, 'nama' => 'Wrong Party', 'penerbit' => 'Unstable Games', 'jumlah' => 1, 'deskripsi_isi' => '1 panduan buku, 152 kartu, 5 topi party, 1 score tracker.', 'kategori' => 'Party', 'jumlah_pemain' => '3-10 Pemain', 'durasi' => '30-45 Menit', 'status' => 'tersedia'],
            ['kode' => '47/DENV/PK/5', 'box' => 'Box 5', 'lantai' => 2, 'nama' => 'Dr. Eureka New Version', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '8 buku panduan bermain, 54 kartu, 8 bola hijau, 8 bola ungu, 8 bola merah, 12 tabung akrilik.', 'kategori' => 'Party & Kecepatan', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '50/MR/PK/5', 'box' => 'Box 5', 'lantai' => 2, 'nama' => 'Moon River', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '4 papan reservasi, 8 meeple ranchero, 96 petak lahan, 20 token mitra, 32 meeple sapi, 1 papan saloon, 1 score pad.', 'kategori' => 'Strategi', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '45-60 Menit', 'status' => 'tersedia'],
            ['kode' => '53/PJ/PK/5', 'box' => 'Box 5', 'lantai' => 1, 'nama' => 'Pengo Jump', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 rules book, 1 sea board, 4 penguin, 1 bag, 18 salju, 6 frosty tile, 6 sea lion beku, 12 sea lion.', 'kategori' => 'Anak-anak', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '5/RA/PK/6', 'box' => 'Box 6', 'lantai' => 2, 'nama' => 'Resistance: Avalon', 'penerbit' => 'Indie Boards & Cards', 'jumlah' => 1, 'deskripsi_isi' => '26 kartu, 25 karton kecil, 1 karton besar, 5 koin besar, 2 koin kecil, 3 lembar tabel vote, 2 panduan bermain.', 'kategori' => 'Sosial Deduksi', 'jumlah_pemain' => '5-10 Pemain', 'durasi' => '30 Menit', 'status' => 'tersedia'],
            ['kode' => '12/HG/PK/6', 'box' => 'Box 6', 'lantai' => 3, 'nama' => 'Halli Galli', 'penerbit' => 'Amigo/Swan', 'jumlah' => 1, 'deskripsi_isi' => '56 kartu, 1 bell, 1 panduan bermain.', 'kategori' => 'Party & Reaksi', 'jumlah_pemain' => '2-6 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '27/C/PK/6', 'box' => 'Box 6', 'lantai' => 3, 'nama' => 'Carcassonne', 'penerbit' => 'Z-Man Games', 'jumlah' => 1, 'deskripsi_isi' => '84 ubin permainan, 1 papan bermain, 45 bidak kayu, 2 lembar panduan bermain, 2 brosur game.', 'kategori' => 'Strategi & Keluarga', 'jumlah_pemain' => '2-5 Pemain', 'durasi' => '35-45 Menit', 'status' => 'dipinjam'],
            ['kode' => '37/UM/PK/6', 'box' => 'Box 6', 'lantai' => 1, 'nama' => 'UNLOCK! Mystery Adventures', 'penerbit' => 'Space Cowboys', 'jumlah' => 1, 'deskripsi_isi' => '3 petualangan (186 kartu), 10 kartu tutorial, 1 buku panduan.', 'kategori' => 'Kooperatif & Escape Room', 'jumlah_pemain' => '1-6 Pemain', 'durasi' => '60 Menit', 'status' => 'dipinjam'],
            ['kode' => '38/UT/PK/6', 'box' => 'Box 6', 'lantai' => 3, 'nama' => 'UNLOCK! Timeless Adventures', 'penerbit' => 'Space Cowboys', 'jumlah' => 1, 'deskripsi_isi' => '10 kartu tutorial, 3 petualangan (180 kartu + 3 lembar kertas), 1 buku panduan.', 'kategori' => 'Kooperatif & Escape Room', 'jumlah_pemain' => '1-6 Pemain', 'durasi' => '60 Menit', 'status' => 'tersedia'],
            ['kode' => '39/USW/PK/6', 'box' => 'Box 6', 'lantai' => 1, 'nama' => 'UNLOCK! Star Wars Adventures', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '3 petualangan (180 kartu), 1 booklet, 1 peta, 10 kartu tutorial, 1 buku panduan.', 'kategori' => 'Kooperatif & Escape Room', 'jumlah_pemain' => '1-6 Pemain', 'durasi' => '60 Menit', 'status' => 'tersedia'],
            ['kode' => '40/S/PK/6', 'box' => 'Box 6', 'lantai' => 1, 'nama' => 'Spellbook', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 rule book, 1 pouch, 1 altar, 1 discard box, 4 familiar board, 4 player aid card, 84 spell card, 105 materia token.', 'kategori' => 'Strategi & Kartu', 'jumlah_pemain' => '2-4 Pemain', 'durasi' => '30-45 Menit', 'status' => 'tersedia'],
            ['kode' => '21/P/PK/7', 'box' => 'Box 7', 'lantai' => 1, 'nama' => 'Polis', 'penerbit' => 'Kosmos', 'jumlah' => 1, 'deskripsi_isi' => '1 papan utama, 2 papan pribadi, 2 lembar informasi pemain, 1 dadu 4 sisi, 168 buah kayu, 14 ubin proyek, 90 kartu.', 'kategori' => 'Strategi Ekonomi', 'jumlah_pemain' => '1-2 Pemain', 'durasi' => '30-45 Menit', 'status' => 'tersedia'],
            ['kode' => '25/A/PK/7', 'box' => 'Box 7', 'lantai' => 1, 'nama' => 'Atiwa', 'penerbit' => 'Lookout Games', 'jumlah' => 1, 'deskripsi_isi' => '1 booklet, 1 rule book, 1 action board, 4 supply board, 52 pohon token, 52 family token, 88 kartu, 200 wooden piece.', 'kategori' => 'Strategi', 'jumlah_pemain' => '1-4 Pemain', 'durasi' => '60-90 Menit', 'status' => 'tersedia'],
            ['kode' => '31/CB/PK/7', 'box' => 'Box 7', 'lantai' => 3, 'nama' => 'Catan (Base)', 'penerbit' => 'Catan Studio', 'jumlah' => 1, 'deskripsi_isi' => '120 kartu, 19 karton hexagonal, 6 karton border, 2 dadu, 24 koin karton, 36 rumah kayu, 60 kayu balok, 1 buku panduan.', 'kategori' => 'Strategi & Keluarga', 'jumlah_pemain' => '3-4 Pemain', 'durasi' => '60-120 Menit', 'status' => 'dipinjam'],
            ['kode' => '43/B/PK/7', 'box' => 'Box 7', 'lantai' => 1, 'nama' => 'Brix', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '22 bricks, 1 rulebook.', 'kategori' => 'Strategi Abstrak', 'jumlah_pemain' => '2 Pemain', 'durasi' => '15 Menit', 'status' => 'tersedia'],
            ['kode' => '56/SQ/PK/7', 'box' => 'Box 7', 'lantai' => 1, 'nama' => 'Slide Quest', 'penerbit' => 'Blue Orange Games', 'jumlah' => 1, 'deskripsi_isi' => '1 papan dengan perangkap, 4 tuas, 20 peta, 1 ksatria bergulir, 8 rintangan, 9 perangkap, 1 buku panduan.', 'kategori' => 'Keluarga & Ketangkasan', 'jumlah_pemain' => '1-4 Pemain', 'durasi' => '20-30 Menit', 'status' => 'tersedia'],
        ];

        foreach ($games as $game) {
            $game['satuan'] = 'set';
            BoardGame::updateOrCreate(['kode' => $game['kode']], $game);
        }
    }
}