<?php

namespace Database\Seeders;

use App\Models\BoardGame;
use Illuminate\Database\Seeder;

class KomponenBilingualSeeder extends Seeder
{
    /**
     * Update kolom `komponen` semua board game jadi format bilingual
     * "English (Indonesian)" per item, supaya toggle EN/ID di web jalan benar.
     * Game dicari berdasarkan kolom `nama` (harus persis sama, case-sensitive).
     */
    public function run(): void
    {
        $data = [
            'Yak' => [
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'punchboard sheet (lembar punchboard)', 'jumlah' => 1],
                ['nama' => 'game board (papan permainan)', 'jumlah' => 1],
                ['nama' => 'bag (kantong)', 'jumlah' => 1],
                ['nama' => 'score pad (blok catatan skor)', 'jumlah' => 1],
                ['nama' => 'baby yak (anak yak)', 'jumlah' => 1],
                ['nama' => 'large yaks (yak besar)', 'jumlah' => 4],
                ['nama' => 'baskets (keranjang)', 'jumlah' => 4],
                ['nama' => 'player boards (papan pemain)', 'jumlah' => 4],
                ['nama' => 'mountain piece (potongan gunung)', 'jumlah' => 1],
                ['nama' => 'stupa marker (penanda stupa)', 'jumlah' => 1],
                ['nama' => 'cloud piece (potongan awan)', 'jumlah' => 1],
                ['nama' => 'cart panels (panel gerobak)', 'jumlah' => 8],
                ['nama' => 'wheels (roda)', 'jumlah' => 8],
                ['nama' => 'fog tokens white (token kabut putih)', 'jumlah' => 5],
                ['nama' => 'bread food tokens yellow (token makanan roti kuning)', 'jumlah' => 15],
                ['nama' => 'milk food tokens white (token makanan susu putih)', 'jumlah' => 15],
                ['nama' => 'chicken food tokens brown (token makanan ayam coklat)', 'jumlah' => 15],
                ['nama' => 'action cards (kartu aksi)', 'jumlah' => 12],
                ['nama' => 'bonus cards (kartu bonus)', 'jumlah' => 8],
                ['nama' => 'crystal stones light blue (batu kristal biru muda)', 'jumlah' => 8],
                ['nama' => 'yellow color stones (batu warna kuning)', 'jumlah' => 8],
                ['nama' => 'orange color stones (batu warna jingga)', 'jumlah' => 8],
                ['nama' => 'tangerine color stones (batu warna oranye)', 'jumlah' => 8],
                ['nama' => 'red color stones (batu warna merah)', 'jumlah' => 8],
                ['nama' => 'dark blue color stones (batu warna biru tua)', 'jumlah' => 8],
                ['nama' => 'dark grey color stones (batu warna abu tua)', 'jumlah' => 8],
                ['nama' => 'light grey color stones (batu warna abu muda)', 'jumlah' => 8],
                ['nama' => 'white horns (tanduk putih)', 'jumlah' => 8],
            ],
            'Imhotep' => [
                ['nama' => 'wooden cubes (kubus kayu)', 'jumlah' => 120],
                ['nama' => 'site boards (papan lokasi)', 'jumlah' => 5],
                ['nama' => 'scoring track (papan jalur skor)', 'jumlah' => 1],
                ['nama' => 'ship tokens (token kapal)', 'jumlah' => 8],
                ['nama' => 'supply sled tokens (token kereta luncur logistik)', 'jumlah' => 4],
                ['nama' => 'round cards (kartu ronde)', 'jumlah' => 21],
                ['nama' => 'market cards (kartu pasar)', 'jumlah' => 34],
                ['nama' => 'rule booklet (buku peraturan)', 'jumlah' => 1],
            ],
            'Ubongo' => [
                ['nama' => 'tiles (ubin)', 'jumlah' => 48],
                ['nama' => 'puzzle boards (papan puzzle)', 'jumlah' => 36],
                ['nama' => 'die (dadu)', 'jumlah' => 1],
                ['nama' => 'hourglass (jam pasir)', 'jumlah' => 1],
                ['nama' => 'cloth bag (kantong kain)', 'jumlah' => 1],
                ['nama' => 'round track board (papan trek ronde permainan)', 'jumlah' => 1],
                ['nama' => 'sapphire gems blue (permata safir biru)', 'jumlah' => 19],
                ['nama' => 'amber gems brown (permata amber coklat)', 'jumlah' => 19],
                ['nama' => 'ruby gems red (permata rubi merah)', 'jumlah' => 10],
                ['nama' => 'emerald gems green (permata zamrud hijau)', 'jumlah' => 10],
            ],
            '1830 : Railways & Robber Barons (1986)' => [
                ['nama' => 'double-sided gameboard (papan permainan dua sisi)', 'jumlah' => 1],
                ['nama' => 'cards (kartu)', 'jumlah' => 117],
                ['nama' => 'corporate charters (piagam perusahaan)', 'jumlah' => 8],
                ['nama' => 'stack of money (tumpukan uang)', 'jumlah' => 1],
                ['nama' => 'hexagonal tiles (ubin heksagonal)', 'jumlah' => 85],
                ['nama' => 'circular tokens (token berbentuk lingkaran)', 'jumlah' => 25],
                ['nama' => 'square markers (penanda berbentuk persegi)', 'jumlah' => 25],
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
            ],
            'Block Ness' => [
                ['nama' => 'Loch board (papan Loch)', 'jumlah' => 1],
                ['nama' => 'monsters in different colors (monster dengan warna berbeda)', 'jumlah' => 4],
                ['nama' => 'head per monster (kepala per monster)', 'jumlah' => 1],
                ['nama' => 'body segments per monster (segmen tubuh per monster)', 'jumlah' => 10],
                ['nama' => 'tail per monster (ekor per monster)', 'jumlah' => 1],
                ['nama' => 'illustrated rulebook in 8 languages (buku aturan bergambar dalam 8 bahasa)', 'jumlah' => 1],
            ],
            'Meeple Land' => [
                ['nama' => 'individual plot boards (papan plot individu)', 'jumlah' => 4],
                ['nama' => 'parking lot board (papan parking lot)', 'jumlah' => 1],
                ['nama' => 'plot extension tiles (ubin plot extension)', 'jumlah' => 4],
                ['nama' => 'extra park entrance tiles (pintu masuk taman tambahan)', 'jumlah' => 4],
                ['nama' => 'small attraction/service tiles with ads on back (ubin attraction/service kecil dengan iklan di bagian belakang)', 'jumlah' => 32],
                ['nama' => 'medium attraction/service tiles (ubin attraction/service sedang)', 'jumlah' => 40],
                ['nama' => 'large attraction/service tiles (ubin attraction/service besar)', 'jumlah' => 29],
                ['nama' => 'bus tiles (ubin bus)', 'jumlah' => 17],
                ['nama' => 'green visitor meeples (meeple pengunjung hijau)', 'jumlah' => 35],
                ['nama' => 'blue visitor meeples (meeple pengunjung biru)', 'jumlah' => 35],
                ['nama' => 'pink visitor meeples (meeple pengunjung merah muda)', 'jumlah' => 30],
                ['nama' => 'yellow visitor meeples (meeple pengunjung kuning)', 'jumlah' => 24],
                ['nama' => 'park tickets token first player (token park tickets pemain pertama)', 'jumlah' => 1],
                ['nama' => 'round marker (penanda ronde)', 'jumlah' => 1],
                ['nama' => '$1 coins (koin $1)', 'jumlah' => 33],
                ['nama' => '$5 coins (koin $5)', 'jumlah' => 19],
                ['nama' => 'player park entrance sets (set pintu masuk taman pemain)', 'jumlah' => 4],
                ['nama' => 'score notebook (buku catatan skor)', 'jumlah' => 1],
                ['nama' => 'rulebook in 7 languages (buku peraturan dalam 7 bahasa)', 'jumlah' => 1],
            ],
            'Photosynthesis' => [
                ['nama' => 'game board (papan permainan)', 'jumlah' => 1],
                ['nama' => 'sun segment (segmen matahari)', 'jumlah' => 1],
                ['nama' => 'player boards (papan pemain)', 'jumlah' => 4],
                ['nama' => 'first player token (token pemain pertama)', 'jumlah' => 1],
                ['nama' => 'score tokens (token skor)', 'jumlah' => 24],
                ['nama' => 'sun marker tokens (token penanda matahari)', 'jumlah' => 4],
                ['nama' => 'number tokens 1-4 (token dengan angka 1-4)', 'jumlah' => 4],
                ['nama' => 'seed tokens 6 per species (token biji 6 tiap spesies)', 'jumlah' => 24],
                ['nama' => 'small trees 8 per species (pohon kecil 8 tiap spesies)', 'jumlah' => 32],
                ['nama' => 'medium trees 4 per species (pohon sedang 4 tiap spesies)', 'jumlah' => 16],
                ['nama' => 'large trees 2 per species (pohon besar 2 tiap spesies)', 'jumlah' => 8],
                ['nama' => 'illustrated rulebook (buku aturan bergambar)', 'jumlah' => 1],
                ['nama' => 'cardboard segments (kardus segmen)', 'jumlah' => 4],
            ],
            'Pengoloo' => [
                ['nama' => 'penguins (pinguin)', 'jumlah' => 12],
                ['nama' => 'red eggs (telur merah)', 'jumlah' => 2],
                ['nama' => 'yellow eggs (telur kuning)', 'jumlah' => 2],
                ['nama' => 'green eggs (telur hijau)', 'jumlah' => 2],
                ['nama' => 'blue eggs (telur biru)', 'jumlah' => 2],
                ['nama' => 'purple eggs (telur ungu)', 'jumlah' => 2],
                ['nama' => 'orange eggs (telur oranye)', 'jumlah' => 2],
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'score boards (papan skor)', 'jumlah' => 4],
                ['nama' => 'dice (dadu)', 'jumlah' => 2],
            ],
            'Tongues Out' => [
                ['nama' => 'dog figures (figur anjing)', 'jumlah' => 12],
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'cards (kartu)', 'jumlah' => 4],
                ['nama' => 'dice (dadu)', 'jumlah' => 2],
            ],
            'The Mind' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 120],
                ['nama' => 'rulebook (panduan bermain)', 'jumlah' => 1],
            ],
            'The Nasty 7' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 110],
                ['nama' => 'rulebook (panduan bermain)', 'jumlah' => 1],
            ],
            'Azul Stained Glass of Sintra' => [
                ['nama' => 'factory displays (pajangan pabrik)', 'jumlah' => 9],
                ['nama' => 'palace boards (papan istana)', 'jumlah' => 4],
                ['nama' => 'pattern strips (strip pola)', 'jumlah' => 32],
                ['nama' => 'glaziers (pengrajin kaca)', 'jumlah' => 4],
                ['nama' => 'markers (penanda)', 'jumlah' => 8],
                ['nama' => 'pane pieces (keping kaca)', 'jumlah' => 100],
                ['nama' => 'scoring board (papan skor)', 'jumlah' => 1],
                ['nama' => 'starting player tile (ubin pemain pertama)', 'jumlah' => 1],
                ['nama' => 'glass tower (menara kaca)', 'jumlah' => 1],
                ['nama' => 'bag (kantong)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
            ],
            'Bendomino' => [
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'domino tiles (ubin domino)', 'jumlah' => 28],
            ],
            'Cupcake Academy' => [
                ['nama' => 'rulebook in 8 languages (buku peraturan dalam 8 bahasa)', 'jumlah' => 1],
                ['nama' => 'pink cupcake molds (cetakan cupcake pink)', 'jumlah' => 4],
                ['nama' => 'green cupcake molds (cetakan cupcake hijau)', 'jumlah' => 4],
                ['nama' => 'yellow cupcake molds (cetakan cupcake kuning)', 'jumlah' => 4],
                ['nama' => 'blue cupcake molds (cetakan cupcake biru)', 'jumlah' => 4],
                ['nama' => 'orange cupcake molds (cetakan cupcake oranye)', 'jumlah' => 4],
                ['nama' => 'pink plates (piring pink)', 'jumlah' => 3],
                ['nama' => 'orange plates (piring oranye)', 'jumlah' => 3],
                ['nama' => 'yellow plates (piring kuning)', 'jumlah' => 3],
                ['nama' => 'blue plates (piring biru)', 'jumlah' => 3],
                ['nama' => 'shared plate (piring bersama)', 'jumlah' => 1],
                ['nama' => 'achievements checklist (daftar pencapaian)', 'jumlah' => 1],
                ['nama' => 'hourglass (jam pasir)', 'jumlah' => 1],
                ['nama' => 'blue cards (kartu biru)', 'jumlah' => 20],
                ['nama' => 'pink cards (kartu pink)', 'jumlah' => 20],
                ['nama' => 'green cards (kartu hijau)', 'jumlah' => 20],
            ],
            'Fish Club' => [
                ['nama' => 'aquarium (akuarium)', 'jumlah' => 1],
                ['nama' => 'red fish (ikan merah)', 'jumlah' => 9],
                ['nama' => 'blue fish (ikan biru)', 'jumlah' => 9],
                ['nama' => 'seahorses (kuda laut)', 'jumlah' => 4],
                ['nama' => 'small fish (ikan kecil)', 'jumlah' => 4],
                ['nama' => 'clams (kerang)', 'jumlah' => 2],
                ['nama' => 'starfish (bintang laut)', 'jumlah' => 2],
                ['nama' => 'sticker set (set stiker)', 'jumlah' => 1],
            ],
            'Snack Match' => [
                ['nama' => 'rulebook in 6 languages (buku peraturan dalam 6 bahasa)', 'jumlah' => 1],
                ['nama' => 'picnic cards (kartu piknik)', 'jumlah' => 72],
                ['nama' => 'bonus cards (kartu bonus)', 'jumlah' => 8],
            ],
            'Who Did It' => [
                ['nama' => 'poop tokens (token kotoran)', 'jumlah' => 13],
                ['nama' => 'rulebook in 8 languages (buku peraturan dalam 8 bahasa)', 'jumlah' => 1],
                ['nama' => 'cards (kartu)', 'jumlah' => 36],
            ],
            'Cookie Box' => [
                ['nama' => 'bell (bel)', 'jumlah' => 1],
                ['nama' => 'order cards (kartu pesanan)', 'jumlah' => 30],
                ['nama' => 'blue order cookies (cookies pesanan biru)', 'jumlah' => 9],
                ['nama' => 'pink order cookies (cookies pesanan pink)', 'jumlah' => 9],
                ['nama' => 'green order cookies (cookies pesanan hijau)', 'jumlah' => 9],
                ['nama' => 'purple order cookies (cookies pesanan ungu)', 'jumlah' => 9],
            ],
            'Kingdomino' => [
                ['nama' => 'domino tiles (ubin domino)', 'jumlah' => 48],
                ['nama' => 'square cards (kartu persegi)', 'jumlah' => 4],
                ['nama' => 'wooden pawns (bidak kayu)', 'jumlah' => 8],
                ['nama' => 'cardboard castles (kastil karton)', 'jumlah' => 4],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
            'Taco Cat Goat Cheese Pizza' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 64],
                ['nama' => 'rulebooks (panduan bermain)', 'jumlah' => 2],
            ],
            'Geistes Blitz' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 60],
                ['nama' => 'chair figure (ornamen kursi)', 'jumlah' => 1],
                ['nama' => 'book figure (ornamen buku)', 'jumlah' => 1],
                ['nama' => 'mouse figure (ornamen tikus)', 'jumlah' => 1],
                ['nama' => 'bottle figure (ornamen botol)', 'jumlah' => 1],
                ['nama' => 'ghost figure (ornamen hantu)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
            'Specific' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 28],
                ['nama' => 'dice (dadu)', 'jumlah' => 3],
                ['nama' => 'rulebook (buku panduan bermain)', 'jumlah' => 1],
            ],
            'Archaeology: The New' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 106],
                ['nama' => 'rulebook (buku panduan bermain)', 'jumlah' => 1],
                ['nama' => 'monument tiles (ubin monumen)', 'jumlah' => 6],
            ],
            'Parade' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 66],
                ['nama' => 'rulebook (panduan bermain)', 'jumlah' => 1],
                ['nama' => 'scorepad (blok skor)', 'jumlah' => 1],
            ],
            'Project L' => [
                ['nama' => 'white puzzles (puzzle putih)', 'jumlah' => 32],
                ['nama' => 'black puzzles (puzzle hitam)', 'jumlah' => 20],
                ['nama' => 'puzzle pieces 10 per 9 shapes (keping puzzle 10 keping dari 9 bentuk)', 'jumlah' => 90],
                ['nama' => 'player mats (alas pemain)', 'jumlah' => 4],
            ],
            'Scout' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 45],
                ['nama' => 'money cards (kartu uang)', 'jumlah' => 23],
                ['nama' => 'number coins (koin angka)', 'jumlah' => 30],
                ['nama' => 'car coins (koin mobil)', 'jumlah' => 5],
                ['nama' => 'pentagon coin (koin segilima)', 'jumlah' => 1],
                ['nama' => 'rulebooks (buku panduan)', 'jumlah' => 3],
            ],
            'Cubeez' => [
                ['nama' => 'rulebook in 8 languages (buku peraturan dalam 8 bahasa)', 'jumlah' => 1],
                ['nama' => 'challenge cards (kartu tantangan)', 'jumlah' => 50],
                ['nama' => 'orange dice (dadu oranye)', 'jumlah' => 3],
                ['nama' => 'yellow dice (dadu kuning)', 'jumlah' => 3],
                ['nama' => 'pink dice (dadu pink)', 'jumlah' => 3],
                ['nama' => 'green dice (dadu hijau)', 'jumlah' => 3],
            ],
            'Next Station: London' => [
                ['nama' => 'colored pencils (pensil berwarna)', 'jumlah' => 4],
                ['nama' => 'square cards (kartu persegi)', 'jumlah' => 9],
                ['nama' => 'blue cards (kartu biru)', 'jumlah' => 6],
                ['nama' => 'pink cards (kartu merah muda)', 'jumlah' => 5],
                ['nama' => 'rulebooks (buku panduan)', 'jumlah' => 7],
                ['nama' => 'score sheets (lembar skor)', 'jumlah' => 1],
            ],
            'Panic Diner' => [
                ['nama' => 'game board (papan permainan)', 'jumlah' => 1],
                ['nama' => 'dishwashing machine box lid (mesin pencuci piring tutup kotak)', 'jumlah' => 1],
                ['nama' => 'double-sided plate tokens (token piring dua sisi)', 'jumlah' => 48],
                ['nama' => 'star tokens (token bintang)', 'jumlah' => 15],
                ['nama' => 'trophy tokens (token trofi)', 'jumlah' => 7],
                ['nama' => 'round customer cards (kartu pelanggan bulat)', 'jumlah' => 40],
                ['nama' => 'square challenge cards (kartu tantangan persegi)', 'jumlah' => 20],
                ['nama' => '90-second hourglass timer (timer jam pasir 90 detik)', 'jumlah' => 1],
                ['nama' => 'illustrated rulebook in 8 languages (buku aturan bergambar dalam 8 bahasa)', 'jumlah' => 1],
            ],
            'Volto' => [
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'red masks (topeng merah)', 'jumlah' => 10],
                ['nama' => 'white masks (topeng putih)', 'jumlah' => 10],
                ['nama' => 'game mat (alas permainan)', 'jumlah' => 1],
            ],
            'Celestia' => [
                ['nama' => 'aircraft (pesawat)', 'jumlah' => 1],
                ['nama' => 'adventurer pawns (bidak petualang)', 'jumlah' => 6],
                ['nama' => 'adventurer tiles (ubin petualang)', 'jumlah' => 6],
                ['nama' => 'oval city tiles (ubin kota berbentuk oval)', 'jumlah' => 9],
                ['nama' => 'event dice (dadu peristiwa)', 'jumlah' => 4],
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
            ],
            'Rhino Hero' => [
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'foundation piece (fondasi)', 'jumlah' => 1],
                ['nama' => 'Rhino Hero figure (figur Rhino Hero)', 'jumlah' => 1],
                ['nama' => 'wall pieces (dinding)', 'jumlah' => 28],
                ['nama' => 'cards (kartu)', 'jumlah' => 31],
            ],
            'Speed Cups' => [
                ['nama' => 'picture cards (kartu gambar)', 'jumlah' => 24],
                ['nama' => 'cups 4 sets of 5 colors (gelas 4 set berisi 5 warna)', 'jumlah' => 20],
            ],
            'The Number' => [
                ['nama' => 'player boards (papan pemain)', 'jumlah' => 5],
                ['nama' => 'number tiles (ubin angka)', 'jumlah' => 5],
                ['nama' => 'dry-erase markers (spidol yang dapat dihapus)', 'jumlah' => 5],
                ['nama' => 'rules book (buku peraturan)', 'jumlah' => 1],
            ],
            'Pandemic (Base)' => [
                ['nama' => 'role cards (kartu peran)', 'jumlah' => 7],
                ['nama' => 'pawns (pion)', 'jumlah' => 7],
                ['nama' => 'city cards (kartu kota)', 'jumlah' => 48],
                ['nama' => 'epidemic cards (kartu epidemi)', 'jumlah' => 6],
                ['nama' => 'event cards (kartu peristiwa)', 'jumlah' => 5],
                ['nama' => 'reference cards (kartu referensi)', 'jumlah' => 4],
                ['nama' => 'infection cards (kartu infeksi)', 'jumlah' => 48],
                ['nama' => 'research stations (stasiun riset)', 'jumlah' => 6],
                ['nama' => 'disease cubes 24 in 4 colors (kubus penyakit 24 dalam 4 warna)', 'jumlah' => 96],
                ['nama' => 'cure markers (penanda obat)', 'jumlah' => 4],
                ['nama' => 'infection rate marker (penanda tingkat infeksi)', 'jumlah' => 1],
                ['nama' => 'outbreaks marker (penanda wabah)', 'jumlah' => 1],
                ['nama' => 'game board (papan permainan)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
            ],
            'Doctor Rat' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 129],
                ['nama' => 'special action tokens (token aksi khusus)', 'jumlah' => 5],
                ['nama' => 'meal counter board (papan penghitung makanan)', 'jumlah' => 1],
                ['nama' => 'rat meeple (meeple tikus)', 'jumlah' => 1],
                ['nama' => 'trash can token (token tempat sampah)', 'jumlah' => 1],
                ['nama' => 'box with a screen and insert (kotak dengan layar dan sisipan)', 'jumlah' => 1],
                ['nama' => 'first player token (token pemain pertama)', 'jumlah' => 1],
                ['nama' => 'rules books (buku peraturan)', 'jumlah' => 2],
            ],
            'Sherlock Express' => [
                ['nama' => 'suspect cards (kartu tersangka)', 'jumlah' => 27],
                ['nama' => 'alibi cards (kartu alibi)', 'jumlah' => 36],
                ['nama' => 'illustrated rulebook in 8 languages (buku aturan bergambar dalam 8 bahasa)', 'jumlah' => 1],
            ],
            'Wonder Woods' => [
                ['nama' => 'wooden baskets (keranjang kayu)', 'jumlah' => 35],
                ['nama' => 'wooden mushrooms (jamur kayu)', 'jumlah' => 56],
                ['nama' => 'first player token (token pemain pertama)', 'jumlah' => 1],
                ['nama' => 'mushroom field boards (papan lahan jamur)', 'jumlah' => 4],
                ['nama' => 'information cards (kartu informasi)', 'jumlah' => 16],
                ['nama' => 'illustrated rulebook (buku aturan bergambar)', 'jumlah' => 1],
            ],
            'Ramen Fury' => [
                ['nama' => 'ramen bowl cards (kartu mangkuk ramen)', 'jumlah' => 15],
                ['nama' => 'ingredient cards (kartu bahan)', 'jumlah' => 89],
                ['nama' => 'spoon tokens (token sendok)', 'jumlah' => 10],
                ['nama' => 'rulebook (buku instruksi)', 'jumlah' => 1],
            ],
            'Sequence' => [
                ['nama' => 'instruction card (kartu instruksi)', 'jumlah' => 1],
                ['nama' => 'game board (papan permainan)', 'jumlah' => 1],
                ['nama' => 'playing cards (kartu main)', 'jumlah' => 104],
                ['nama' => 'red marker chips (keping penanda merah)', 'jumlah' => 35],
                ['nama' => 'blue marker chips (keping penanda biru)', 'jumlah' => 50],
                ['nama' => 'green marker chips (keping penanda hijau)', 'jumlah' => 50],
            ],
            'Spot it (Eco Blister/Peg)' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 55],
                ['nama' => 'tin can (kaleng)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
                ['nama' => 'mini games (mini game)', 'jumlah' => 5],
            ],
            'Get Bit' => [
                ['nama' => 'swimmer figures (figur perenang)', 'jumlah' => 6],
                ['nama' => 'shark figure (figur hiu lapar)', 'jumlah' => 1],
                ['nama' => 'rulebook (panduan bermain)', 'jumlah' => 1],
            ],
            'Rustling Leaves' => [
                ['nama' => 'score sheet (lembar skor)', 'jumlah' => 1],
                ['nama' => 'dice (dadu)', 'jumlah' => 2],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
            'Timeline Events' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 55],
                ['nama' => 'tin can (kaleng)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
            'Timeline Inventions' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 55],
                ['nama' => 'tin can (kaleng)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
            'Wrong Party' => [
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
                ['nama' => 'cards (kartu)', 'jumlah' => 152],
                ['nama' => 'party hats (topi pesta)', 'jumlah' => 5],
                ['nama' => 'score tracker (pelacak skor)', 'jumlah' => 1],
            ],
            'Dr. Eureka New Version' => [
                ['nama' => 'rulebook in 8 languages (buku panduan bermain dalam 8 bahasa)', 'jumlah' => 1],
                ['nama' => 'cards (kartu)', 'jumlah' => 54],
                ['nama' => 'green balls (bola hijau)', 'jumlah' => 8],
                ['nama' => 'purple balls (bola ungu)', 'jumlah' => 8],
                ['nama' => 'red balls (bola merah)', 'jumlah' => 8],
                ['nama' => 'acrylic tubes (tabung akrilik)', 'jumlah' => 12],
            ],
            'Moon River' => [
                ['nama' => 'reservation boards (papan reservasi)', 'jumlah' => 4],
                ['nama' => 'ranchero meeples (meeple ranchero)', 'jumlah' => 8],
                ['nama' => 'plots (petak lahan)', 'jumlah' => 96],
                ['nama' => 'partner tokens (token mitra)', 'jumlah' => 20],
                ['nama' => 'cow meeples (meeple sapi)', 'jumlah' => 32],
                ['nama' => 'landscape bonus tiles (ubin bonus lanskap)', 'jumlah' => 2],
                ['nama' => 'saloon board (papan saloon)', 'jumlah' => 1],
                ['nama' => 'score pad (buku lembar skor)', 'jumlah' => 1],
            ],
            'Pengo Jump' => [
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'sea board (papan laut)', 'jumlah' => 1],
                ['nama' => 'penguins (pinguin)', 'jumlah' => 4],
                ['nama' => 'bag (kantong)', 'jumlah' => 1],
                ['nama' => 'snow pieces (potongan salju)', 'jumlah' => 18],
                ['nama' => 'frosty tiles (ubin beku)', 'jumlah' => 6],
                ['nama' => 'frozen sea lions (singa laut beku)', 'jumlah' => 6],
                ['nama' => 'small sea lions (singa laut kecil)', 'jumlah' => 6],
                ['nama' => 'large sea lions (singa laut besar)', 'jumlah' => 6],
            ],
            'Resistance Avalon' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 26],
                ['nama' => 'small cardboard tokens (karton kecil)', 'jumlah' => 25],
                ['nama' => 'large cardboard token (karton besar)', 'jumlah' => 1],
                ['nama' => 'large coins (koin besar)', 'jumlah' => 5],
                ['nama' => 'small coins (koin kecil)', 'jumlah' => 2],
                ['nama' => 'vote table sheets (lembar tabel vote)', 'jumlah' => 3],
                ['nama' => 'rulebooks (panduan bermain)', 'jumlah' => 2],
            ],
            'Halli Galli' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 56],
                ['nama' => 'bell (bel)', 'jumlah' => 1],
                ['nama' => 'rulebook (panduan bermain)', 'jumlah' => 1],
            ],
            'Carcassonne' => [
                ['nama' => 'game tiles (ubin permainan)', 'jumlah' => 84],
                ['nama' => 'game board (papan bermain)', 'jumlah' => 1],
                ['nama' => 'wooden pawns (bidak kayu)', 'jumlah' => 45],
                ['nama' => 'rulebook sheets (lembar panduan bermain)', 'jumlah' => 2],
                ['nama' => 'game brochures (brosur game)', 'jumlah' => 2],
            ],
            'UNLOCK! Mystery' => [
                ['nama' => 'adventures 186 cards total (petualangan 186 kartu)', 'jumlah' => 3],
                ['nama' => 'tutorial cards (kartu tutorial)', 'jumlah' => 10],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
            'UNLOCK! Timeless' => [
                ['nama' => 'tutorial cards (kartu tutorial)', 'jumlah' => 10],
                ['nama' => 'adventures 180 cards + 3 sheets (petualangan 180 kartu + 3 lembar kertas)', 'jumlah' => 3],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
            'UNLOCK! Stars Wars' => [
                ['nama' => 'adventures 180 cards (petualangan 180 kartu)', 'jumlah' => 3],
                ['nama' => 'booklet (buklet)', 'jumlah' => 1],
                ['nama' => 'map (peta)', 'jumlah' => 1],
                ['nama' => 'tutorial cards (kartu tutorial)', 'jumlah' => 10],
                ['nama' => 'paper sheet (lembar kertas)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
            'Spellbook' => [
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'pouch (kantong)', 'jumlah' => 1],
                ['nama' => 'altar grey (altar abu-abu)', 'jumlah' => 1],
                ['nama' => 'discard box brown wood (kotak buangan kayu coklat)', 'jumlah' => 1],
                ['nama' => 'first player token book-shaped (token pemain pertama bentuk buku)', 'jumlah' => 1],
                ['nama' => 'familiar boards (papan familiar)', 'jumlah' => 4],
                ['nama' => 'player aid cards (kartu bantuan pemain)', 'jumlah' => 4],
                ['nama' => 'spell cards (kartu mantra)', 'jumlah' => 84],
                ['nama' => 'materia tokens (token materia)', 'jumlah' => 105],
            ],
            'Polis' => [
                ['nama' => 'main board (papan utama)', 'jumlah' => 1],
                ['nama' => 'personal boards (papan pribadi)', 'jumlah' => 2],
                ['nama' => 'player info sheets (lembar informasi pemain)', 'jumlah' => 2],
                ['nama' => 'four-sided die (dadu empat sisi)', 'jumlah' => 1],
                ['nama' => 'wooden pieces (buah kayu)', 'jumlah' => 168],
                ['nama' => 'project tiles (ubin proyek)', 'jumlah' => 14],
                ['nama' => 'sheets (lembar)', 'jumlah' => 4],
                ['nama' => 'cards (kartu)', 'jumlah' => 90],
            ],
            'Atiwa' => [
                ['nama' => 'booklet (buklet)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
                ['nama' => 'action board (papan aksi)', 'jumlah' => 1],
                ['nama' => 'action board extensions (perluasan papan aksi)', 'jumlah' => 2],
                ['nama' => 'supply boards (papan persediaan)', 'jumlah' => 4],
                ['nama' => 'action spaces (ruang aksi)', 'jumlah' => 6],
                ['nama' => 'tree tokens (token pohon)', 'jumlah' => 52],
                ['nama' => 'family tokens (token keluarga)', 'jumlah' => 52],
                ['nama' => 'first player token (token pemain pertama)', 'jumlah' => 1],
                ['nama' => 'single-value gold tokens (token emas satuan)', 'jumlah' => 25],
                ['nama' => 'gold tokens value 5 (token emas angka 5)', 'jumlah' => 15],
                ['nama' => 'zero-pollution tokens (token polusi nol)', 'jumlah' => 22],
                ['nama' => 'one-pollution tokens (token polusi satu)', 'jumlah' => 20],
                ['nama' => 'two-pollution tokens (token polusi dua)', 'jumlah' => 2],
                ['nama' => 'cloth bag (kantong kain)', 'jumlah' => 1],
                ['nama' => 'scoring pad (blok skor)', 'jumlah' => 1],
                ['nama' => 'cards (kartu)', 'jumlah' => 88],
                ['nama' => 'white goats (kambing putih)', 'jumlah' => 28],
                ['nama' => 'orange fruits (buah oranye)', 'jumlah' => 32],
                ['nama' => 'beige wild animals (hewan liar krem)', 'jumlah' => 32],
                ['nama' => 'black fruit bats (kelelawar buah hitam)', 'jumlah' => 96],
                ['nama' => 'red player tokens (token pemain merah)', 'jumlah' => 3],
                ['nama' => 'blue player tokens (token pemain biru)', 'jumlah' => 3],
                ['nama' => 'grey player tokens (token pemain abu-abu)', 'jumlah' => 3],
                ['nama' => 'yellow player tokens (token pemain kuning)', 'jumlah' => 3],
            ],
            'Catan (Base)' => [
                ['nama' => 'cards (kartu)', 'jumlah' => 120],
                ['nama' => 'hexagonal cardboard tiles (ubin karton heksagonal)', 'jumlah' => 19],
                ['nama' => 'border cardboard tiles (ubin karton border)', 'jumlah' => 6],
                ['nama' => 'dice (dadu)', 'jumlah' => 2],
                ['nama' => 'cardboard cards (kartu karton)', 'jumlah' => 6],
                ['nama' => 'cardboard coins (koin karton)', 'jumlah' => 24],
                ['nama' => 'cardboard ships (kapal karton)', 'jumlah' => 9],
                ['nama' => 'wooden houses (rumah kayu)', 'jumlah' => 36],
                ['nama' => 'wooden pawn (pion kayu)', 'jumlah' => 1],
                ['nama' => 'wooden blocks (balok kayu)', 'jumlah' => 60],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
                ['nama' => 'brochure (brosur)', 'jumlah' => 1],
                ['nama' => 'brochure booklet (buku brosur)', 'jumlah' => 1],
            ],
            'Brix' => [
                ['nama' => 'bricks (balok)', 'jumlah' => 22],
                ['nama' => 'rulebook (buku peraturan)', 'jumlah' => 1],
            ],
            'Slide Quest' => [
                ['nama' => 'board with traps (papan dengan perangkap)', 'jumlah' => 1],
                ['nama' => 'levers (tuas)', 'jumlah' => 4],
                ['nama' => 'maps featuring 4 world types (peta yang menampilkan 4 jenis dunia)', 'jumlah' => 20],
                ['nama' => 'rolling knight figure (ksatria bergulir)', 'jumlah' => 1],
                ['nama' => 'arch gates (gerbang lengkung)', 'jumlah' => 2],
                ['nama' => 'large barriers (penghalang besar)', 'jumlah' => 2],
                ['nama' => 'small barriers (penghalang kecil)', 'jumlah' => 2],
                ['nama' => 'large rocks (batu besar)', 'jumlah' => 2],
                ['nama' => 'dynamite traps (perangkap dinamit)', 'jumlah' => 4],
                ['nama' => 'numbered guard traps 1-4 (perangkap penjaga bernomor 1 sampai 4)', 'jumlah' => 4],
                ['nama' => 'villain trap (perangkap penjahat)', 'jumlah' => 1],
                ['nama' => 'life counter (penghitung nyawa)', 'jumlah' => 1],
                ['nama' => 'difficulty levels (tingkat kesulitan)', 'jumlah' => 3],
                ['nama' => 'heart marker (penanda hati)', 'jumlah' => 1],
                ['nama' => 'game saver piece (penyelamat permainan)', 'jumlah' => 1],
                ['nama' => 'rulebook (buku panduan)', 'jumlah' => 1],
            ],
        ];

        $updated = 0;
        $notFound = [];

        foreach ($data as $namaGame => $komponen) {
            $game = BoardGame::where('nama', $namaGame)->first();

            if (!$game) {
                $notFound[] = $namaGame;
                continue;
            }

            $game->komponen = $komponen;
            $game->save();
            $updated++;
        }

        $this->command->info("Berhasil update komponen untuk {$updated} board game.");

        if (count($notFound) > 0) {
            $this->command->warn('Nama game berikut TIDAK ditemukan di database (cek ejaan/kapitalisasi):');
            foreach ($notFound as $n) {
                $this->command->warn("  - {$n}");
            }
        }
    }
}