import { createContext, useContext, useEffect, useState } from "react";

const KUNCI_PENYIMPANAN = "bahasa";

export function useBahasaState() {
    const [bahasa, setBahasa] = useState(() => {
        if (typeof window === "undefined") return "ID";
        return localStorage.getItem(KUNCI_PENYIMPANAN) || "ID";
    });

    useEffect(() => {
        localStorage.setItem(KUNCI_PENYIMPANAN, bahasa);
    }, [bahasa]);

    return [bahasa, setBahasa];
}

export const TEKS = {
    ID: {
        cariPlaceholder: "Cari nama board game...",
        masuk: "Masuk",
        favorit: "Favorit",
        riwayat: "Riwayat",
        filter: "Filter:",
        kategori: "Kategori",
        lantai: "Lantai",
        status: "Status",
        semua: "Semua",
        tersedia: "Tersedia",
        dipinjam: "Dipinjam",
        umum: "Umum",
        boardGame: "board game",
        tersediaDipinjam: "Tersedia untuk Dipinjam",
        sedangDipinjam: "Sedang Dipinjam",
        pinjam: "Pinjam",
        lihatDetail: "Lihat Detail",
        tidakCocok: "Tidak ada board game yang cocok dengan filter ini.",
        rekomendasi: "Rekomendasi",
        produkPopuler: "Produk Paling Populer",
        informasi: "Informasi",
        tataCaraJudul: "Tata Cara Peminjaman",
        pemain: "Pemain",
        menit: "Menit",
        kembali: "Kembali ke Katalog",
        kode: "Kode",
        box: "Box",
        penerbit: "Penerbit",
        deskripsiIsi: "Lihat Detail",
        detailBoardGame: "Detail Board Game",
        informasiUmum: "Informasi Umum",
        usia: "Usia",
        kesulitan: "Kesulitan",
        ringan: "Ringan",
        sedang: "Sedang",
        berat: "Berat",
        gameSerupa: "Game Serupa Lainnya",
        gameSerupaSub: "Kategori sama dengan game ini",
        deskripsiGame: "Deskripsi",
        videoTutorial: "Video Tutorial",
        tontonTutorial: "Tonton Cara Bermain",
        panduanBermain: "Panduan Bermain",
        reviewHeading: "Review",
        tulisReview: "Tulis Review",
        ratingLabel: "Rating",
        komentarLabel: "Komentar",
        kirimReview: "Kirim Review",
        mengirim: "Mengirim...",
        belumAdaReview: "Belum ada review untuk board game ini.",
        belumAdaRating: "Belum ada rating",
        pinjamSekarang: "Pinjam Sekarang",
        klikDetail: "Klik untuk melihat detail",
        tutup: "Tutup",
        tataCaraPoin: [
            "Peminjam melakukan peminjaman langsung di meja layanan kepada petugas yang bertugas",
            "Peminjam memilih board game yang ingin dipinjam, lalu melengkapi form peminjaman sebelum mengambil barangnya",
            "Peminjam menyerahkan satu kartu identitas (KTM/KTP/Kartu Anggota Perpustakaan) kepada petugas sebagai jaminan",
            "Peminjam bersama petugas memeriksa kelengkapan komponen (kartu, dadu, pion, papan, dan lain-lain) sesuai lembar daftar isi pada kotak, sebelum board game dibawa ke meja permainan",
            "Peminjam hanya boleh memainkan board game di lantai tempat board game tersebut dipinjam, tidak membawanya ke lantai lain maupun membawanya pulang",
            "Peminjam menjaga kelengkapan komponen permainan selama masa peminjaman berlangsung, dan tidak memindahtangankan board game ke kelompok lain secara sepihak.",
            "Peminjam meminjam dan mengembalikan board game pada hari yang sama, paling lambat sebelum jam operasional perpustakaan berakhir",
            "Peminjam menerima kembali kartu identitasnya setelah board game diperiksa petugas dan dinyatakan lengkap",
        ],
        sanksiJudul: "Sanksi Kerusakan / Kehilangan",
        sanksiPoin: [
            "Komponen hilang: wajib ganti sesuai jenis komponen",
            "Board game rusak: wajib ganti unit yang sama",
            "Board game hilang: ganti unit baru atau denda sesuai ketentuan",
        ],
        carousel: [
            {
                title: "Selamat Datang di UPT Perpustakaan Universitas Diponegoro dan UNDIP Press",
                description: "Temukan, pilih, dan pinjam board game favoritmu melalui katalog digital UPT Perpustakaan Universitas Diponegoro.",
                detailTitle: "Selamat Datang di Board Game\nUPT Perpustakaan Undip",
                detailDescription: "Katalog board game ini membantu pemustaka mencari informasi permainan, melihat detail board game, dan mengajukan peminjaman secara online.",
                points: [
                    "Cari board game berdasarkan nama, kategori, lantai, dan status.",
                    "Lihat detail board game sebelum mengajukan peminjaman.",
                    "Ajukan peminjaman melalui tombol Pinjam.",
                    "Gunakan board game hanya di area perpustakaan.",
                ],
                theme: "welcome",
                bgImage: "https://images.pexels.com/photos/37983585/pexels-photo-37983585.jpeg",
            },
            {
                title: "Tata Cara Peminjaman",
                description: "Ikuti prosedur peminjaman sebelum mengambil board game.",
                detailTitle: "Tata Cara Peminjaman Board Game",
                detailDescription: "Pemustaka wajib mengikuti prosedur peminjaman board game di UPT Perpustakaan Universitas Diponegoro.",
                points: [
                    "Peminjam melakukan peminjaman langsung di meja layanan kepada petugas yang bertugas",
                    "Peminjam memilih board game yang ingin dipinjam, lalu melengkapi form peminjaman sebelum mengambil barangnya",
                    "Peminjam menyerahkan satu kartu identitas (KTM/KTP/Kartu Anggota Perpustakaan) kepada petugas sebagai jaminan",
                    "Peminjam bersama petugas memeriksa kelengkapan komponen (kartu, dadu, pion, papan, dan lain-lain) sesuai lembar daftar isi pada kotak, sebelum board game dibawa ke meja permainan",
                    "Peminjam hanya boleh memainkan board game di lantai tempat board game tersebut dipinjam, tidak membawanya ke lantai lain maupun membawanya pulang",
                    "Peminjam menjaga kelengkapan komponen permainan selama masa peminjaman berlangsung, dan tidak memindahtangankan board game ke kelompok lain secara sepihak.",
                    "Peminjam meminjam dan mengembalikan board game pada hari yang sama, paling lambat sebelum jam operasional perpustakaan berakhir",
                    "Peminjam menerima kembali kartu identitasnya setelah board game diperiksa petugas dan dinyatakan lengkap",
                ],
                theme: "procedure",
                bgImage: "https://images.pexels.com/photos/6333905/pexels-photo-6333905.jpeg?_gl=1*1dwbmw3*_ga*NzkwNzYzNjA5LjE3ODQwMTI3MDg.*_ga_8JE65Q40S6*czE3ODQ2MjAwOTckbzYkZzEkdDE3ODQ2MjAwOTgkajU5JGwwJGgw",
            },
            {
                title: "Ketentuan Penggunaan",
                description: "Jaga kelengkapan dan kondisi board game selama masa peminjaman.",
                detailTitle: "Ketentuan Penggunaan Board Game",
                detailDescription: "Peminjam bertanggung jawab menjaga kondisi dan kelengkapan board game selama digunakan.",
                points: [
                    "Peminjam bertanggung jawab penuh atas keutuhan fisik board game yang digunakannya selama masa peminjaman",
                    "Jika ada komponen yang hilang atau rusak, peminjam wajib menggantinya dengan board game yang judul dan penerbitnya sama persis",
                    "Kerusakan yang dimaksud mencakup antara lain kartu yang sobek, kotak yang penyok cukup parah, atau komponen permainan yang hilang sebagian, bukan hanya kehilangan seluruh set",
                    "Apabila board game tersebut sudah tidak beredar lagi di pasaran, peminjam dapat menggantinya dengan board game lain yang setara, baik dari segi jenis permainan maupun harga, bukan dalam bentuk uang tunai.",
                    "Peminjam diberi waktu paling lama empat belas hari kerja sejak kehilangan atau kerusakan dilaporkan untuk menyelesaikan penggantian",
                    "Selama proses penggantian belum diselesaikan, kartu identitas peminjam ditahan oleh petugas layanan",
                    "Selama kasus penggantian ini belum terselesaikan, peminjam belum diperkenankan meminjam board game lain",
                ],
                theme: "rules",
                bgImage: "https://images.pexels.com/photos/33152331/pexels-photo-33152331.jpeg?_gl=1*1wmu6ve*_ga*NzkwNzYzNjA5LjE3ODQwMTI3MDg.*_ga_8JE65Q40S6*czE3ODQ2MTc0OTckbzUkZzEkdDE3ODQ2MTc1NzgkajU5JGwwJGgw",
            },
            {
                title: "Sanksi Kerusakan / Kehilangan",
                description: "Ketahui konsekuensi jika komponen atau board game rusak maupun hilang.",
                detailTitle: "Sanksi Kerusakan / Kehilangan Board Game",
                detailDescription: "Peminjam wajib mengganti sesuai ketentuan apabila terjadi kerusakan atau kehilangan komponen maupun board game.",
                points: [
                    "Komponen hilang: wajib ganti sesuai jenis komponen",
                    "Board game rusak: wajib ganti unit yang sama",
                    "Board game hilang: ganti unit baru atau denda sesuai ketentuan",
                ],
                theme: "sanksi",
                bgImage: "https://images.pexels.com/photos/8899971/pexels-photo-8899971.jpeg?_gl=1*g5dap3*_ga*NzkwNzYzNjA5LjE3ODQwMTI3MDg.*_ga_8JE65Q40S6*czE3ODQ2MjAwOTckbzYkZzEkdDE3ODQ2MjA5MDgkajU5JGwwJGgw",
            },
        ],
    },
    EN: {
        cariPlaceholder: "Search board game name...",
        masuk: "Sign In",
        favorit: "Favorites",
        riwayat: "History",
        filter: "Filter:",
        kategori: "Category",
        lantai: "Floor",
        status: "Status",
        semua: "All",
        tersedia: "Available",
        dipinjam: "Borrowed",
        umum: "General",
        boardGame: "board games",
        tersediaDipinjam: "Available to Borrow",
        sedangDipinjam: "Currently Borrowed",
        pinjam: "Borrow",
        lihatDetail: "View Details",
        tidakCocok: "No board games match this filter.",
        rekomendasi: "Recommended",
        produkPopuler: "Most Popular Titles",
        informasi: "Information",
        tataCaraJudul: "How to Borrow",
        pemain: "Players",
        menit: "Minutes",
        kembali: "Back to Catalog",
        kode: "Code",
        box: "Box",
        penerbit: "Publisher",
        deskripsiIsi: "Components",
        detailBoardGame: "Board Game Detail",
        informasiUmum: "General Information",
        usia: "Age",
        kesulitan: "Difficulty",
        ringan: "Light",
        sedang: "Medium",
        berat: "Heavy",
        gameSerupa: "More Similar Games",
        gameSerupaSub: "Same category as this game",
        deskripsiGame: "Description",
        videoTutorial: "Tutorial Video",
        tontonTutorial: "Watch How to Play",
        panduanBermain: "Rulebook",
        reviewHeading: "Review",
        tulisReview: "Write a Review",
        ratingLabel: "Rating",
        komentarLabel: "Comment",
        kirimReview: "Submit Review",
        mengirim: "Sending...",
        belumAdaReview: "No reviews for this board game yet.",
        belumAdaRating: "No ratings yet",
        pinjamSekarang: "Borrow Now",
        klikDetail: "Click to view details",
        tutup: "Close",
        tataCaraPoin: [
            "Fill out the borrowing form through the system before picking up the board game",
            "Hand over an ID card (student card/ID/KTP) to staff as a deposit",
            "Board games may only be played inside the library, not taken home",
            "Return it the same day, by the planned return time entered when borrowing",
            "Keep all components (cards, dice, pawns, board, etc.) intact during use",
            "Your ID card is returned once the board game is checked and confirmed complete",
        ],
        sanksiJudul: "Damage / Loss Penalty",
        sanksiPoin: [
            "Missing component: must be replaced with the matching piece",
            "Damaged game: must be replaced with the same unit",
            "Lost game: replace with a new unit or pay a fine per policy",
        ],
        carousel: [
            {
                title: "Welcome to UPT Perpustakaan Universitas Diponegoro and UNDIP Press",
                description: "Discover, choose, and borrow your favorite board games through the digital catalog of UPT Library of Diponegoro University.",
                detailTitle: "Welcome to Board Game\nUPT Library Undip",
                detailDescription: "This board game catalog helps students find game information, view board game details, and submit borrowing requests online.",
                points: [
                    "Search board games by name, category, floor, and status.",
                    "View board game details before submitting a borrowing request.",
                    "Submit a borrowing request through the Borrow button.",
                    "Play board games only in the library area.",
                ],
                theme: "welcome",
                bgImage: "https://images.pexels.com/photos/37983585/pexels-photo-37983585.jpeg",
            },
            {
                title: "How to Borrow",
                description: "Follow the borrowing procedure before taking a board game.",
                detailTitle: "How to Borrow Board Games",
                detailDescription: "Students must follow the board game borrowing procedure at UPT Library of Diponegoro University.",
                points: [
                    "Fill out the borrowing form through the system before picking up the board game.",
                    "Hand over your ID card as a deposit.",
                    "Board games may only be played in the library area.",
                    "Return on the same day according to the planned return time.",
                ],
                theme: "procedure",
                bgImage: "https://images.pexels.com/photos/6333905/pexels-photo-6333905.jpeg?_gl=1*1dwbmw3*_ga*NzkwNzYzNjA5LjE3ODQwMTI3MDg.*_ga_8JE65Q40S6*czE3ODQ2MjAwOTckbzYkZzEkdDE3ODQ2MjAwOTgkajU5JGwwJGgw",
            },
            {
                title: "Usage Rules",
                description: "Keep the board game components and condition during the borrowing period.",
                detailTitle: "Board Game Usage Rules",
                detailDescription: "Borrowers are responsible for maintaining the condition and completeness of the board game during use.",
                points: [
                    "Keep components such as cards, dice, pawns, boards, and rulebooks.",
                    "Report to staff if any components are damaged or missing.",
                    "ID cards are returned after the board game is checked.",
                    "Use board games properly in the library area.",
                ],
                theme: "rules",
                bgImage: "https://images.pexels.com/photos/33152331/pexels-photo-33152331.jpeg?_gl=1*1wmu6ve*_ga*NzkwNzYzNjA5LjE3ODQwMTI3MDg.*_ga_8JE65Q40S6*czE3ODQ2MTc0OTckbzUkZzEkdDE3ODQ2MTc1NzgkajU5JGwwJGgw",
            },
            {
                title: "Damage / Loss Penalty",
                description: "Know the consequences if components or the board game are damaged or lost.",
                detailTitle: "Board Game Damage / Loss Penalty",
                detailDescription: "Borrowers must replace items according to policy if components or the board game are damaged or lost.",
                points: [
                    "Missing component: must be replaced with the matching piece",
                    "Damaged game: must be replaced with the same unit",
                    "Lost game: replace with a new unit or pay a fine per policy",
                ],
                theme: "sanksi",
                bgImage: "https://images.pexels.com/photos/8899971/pexels-photo-8899971.jpeg?_gl=1*g5dap3*_ga*NzkwNzYzNjA5LjE3ODQwMTI3MDg.*_ga_8JE65Q40S6*czE3ODQ2MjAwOTckbzYkZzEkdDE3ODQ2MjA5MDgkajU5JGwwJGgw",
            },
        ],
    },
};

export const BahasaContext = createContext(TEKS.ID);
export function useTeks() {
    return useContext(BahasaContext);
}

